hmrc/charities-registration-frontend

- app/views/govuk_wrapper.scala.html
- app/views/home/eligibility.scala.html
- app/views/home/ineligible.scala.html
- app/views/home/ukBased.scala.html
- app/views/home/validBank.scala.html
- app/views/home/validCountries.scala.html
- app/views/main_template.scala.html
- conf/messages
- test/views/CharitableEligibilityControllerViewSpec.scala
- test/views/IneligibleForRegistrationControllerViewSpec.scala
- test/views/UKBasedEligibilityControllerViewSpec.scala
- test/views/ValidBankEligibilityControllerViewSpec.scala
- test/views/ValidCountriesEligibilityControllerViewSpec.scala
**Bugfix- DDCE-421, 456**
I've included appropriate unit test and all tests passed
I've added my code using logical, atomic commits, squashing as appropriate - including the JIRA issue number in the commit message
> [DDCE-421, 456]:Error summary and Back link issues

- .github/PULL_REQUEST_TEMPLATE.md
- .gitignore
- app/controllers/ValidCountriesEligibilityController.scala
- test/controllers/ValidCountriesEligibilityControllerSpec.scala
**Bugfix - DDCE-473:Amend redirect after selecting 'No' for Eligibility Question 4**
Eligibility Question 4 page should redirect to Not eligible page if user selects No, but it was not working as expected. Fixed this issue.
- I've included appropriate unit test with any code I've added 
- I've added my code using logical, atomic commits, squashing as appropriate - including the JIRA issue number in the commit message
> [DDCE-473]:Eligibility Qn 4 is not redirecting to Ineligible page

- app/controllers/LanguageSwitchController.scala
- app/views/components/languageSelection.scala.html
- app/views/govuk_wrapper.scala.html
- conf/app.routes
- conf/application.conf
- conf/messages.cy
- conf/messages.en
- test/util/MessagesSpec.scala
- test/views/components/LanguageSelectionSpec.scala
> [DDCE-367]:Configure LanguageSwitchController for Welsh language

- app/config/AppConfig.scala
- app/views/govuk_wrapper.scala.html
- build.sbt
- conf/application.conf
- conf/prod.routes
- project/AppDependencies.scala
- project/plugins.sbt
- test/controllers/CharitableEligibilityControllerSpec.scala
- test/controllers/UKBasedEligibilityControllerSpec.scala
- test/controllers/ValidBankEligibilityControllerSpec.scala
- test/controllers/ValidCountriesEligibilityControllerSpec.scala
- test/controllers/auth/AuthActionSpec.scala
##Bug fix
Changed domain name for charities registration
> DDCE-497-changed domain name

- build.sbt
- conf/application.conf
> DDCE-534: updated app name

- conf/checkEligibility.routes
> DDCE-545:Amendment for eligibility question 2

- conf/checkEligibility.routes
> DDCE:540-Amendments for not eligible page

- app/views/checkEligibility/IsEligibleLocationOtherView.scala.html
- conf/checkEligibility.routes
- conf/messages.cy
- conf/messages.en
> DDCE-547 : Amend Eligibility question 4: Is your charity based in the European Union, Iceland, Liechtenstein or Norway?

- app/controllers/contact/CharityUKAddressController.scala
- app/forms/contact/CharityUKAddressFormProvider.scala
- app/models/ContactModels.scala
- app/navigation/ContactNavigator.scala
- app/pages/contact/CharityUKAddressPage.scala
- app/views/contact/CharityUKAddressView.scala.html
- conf/contact.routes
- conf/messages.cy
- conf/messages.en
- test/controllers/SessionExpiredControllerSpec.scala
- test/controllers/contact/CharityUKAddressControllerSpec.scala
- test/forms/contact/CharityUKAddressFormProviderSpec.scala
- test/navigation/ContactNavigatorSpec.scala
- test/pages/contact/CharityUKAddressPageSpec.scala
- test/views/behaviours/ViewBehaviours.scala
- test/views/contact/CharityUKAddressViewSpec.scala
> DDCE-445:Charity UK Address fill manually

- app/controllers/contact/IsCharityOfficialAddressInUKController.scala
- app/forms/contact/IsCharityOfficialAddressInUKFormProvider.scala
- app/navigation/ContactNavigator.scala
- app/pages/contact/IsCharityOfficialAddressInUKPage.scala
- app/views/contact/IsCharityOfficialAddressInUKView.scala.html
- conf/contact.routes
- conf/messages.cy
- conf/messages.en
- test/controllers/contact/IsCharityOfficialAddressInUKControllerSpec.scala
- test/forms/contact/IsCharityOfficialAddressInUKPageFormProviderSpec.scala
- test/navigation/ContactNavigatorSpec.scala
- test/pages/contact/IsCharityOfficialAddressInUKPageSpec.scala
- test/views/contact/IsCharityOfficialAddressInUKViewSpec.scala
P3 - Is your charity's official address in the UK?
> Ddce 412 new

- app/config/FrontendAppConfig.scala
- app/views/components/siteHeader.scala.html
- test/views/components/SiteHeaderSpec.scala
> DDCE:558-Banner changes and commits squashed

- app/views/charityInformation/CharityNameView.scala.html
- app/views/charityInformation/IsCharityOfficialAddressInUKView.scala.html
- conf/messages.cy
- conf/messages.en
- test/views/charityInformation/CharityNameViewSpec.scala
- test/views/charityInformation/IsCharityOfficialAddressInUKViewSpec.scala
> DDCE-549:Page title Amendments for section one pages

- app/views/charityInformation/CharityContactDetailsView.scala.html
- app/views/charityInformation/CharityUKAddressView.scala.html
- conf/messages.cy
- conf/messages.en
- test/forms/charityInformation/CharityContactDetailsFormProviderSpec.scala
- test/views/charityInformation/CharityContactDetailsViewSpec.scala
- test/views/charityInformation/CharityUKAddressViewSpec.scala
##Bug fix
Amend §1 P1 & P2 - Charity's contact details
> DDCE-561 Amend §1 P1 & P2 - Charity's contact details

- app/controllers/IndexController.scala
- app/controllers/actions/IdentifierAction.scala
- app/controllers/charityInformation/CharityContactDetailsController.scala
- app/controllers/charityInformation/CharityNameController.scala
- app/controllers/charityInformation/CharityUKAddressController.scala
- app/controllers/charityInformation/IsCharityOfficialAddressInUKController.scala
- app/controllers/checkEligibility/IsEligiblePurposeController.scala
- app/models/TaskList.scala
- app/navigation/CharityInformationNavigator.scala
- app/pages/Section1Page.scala
- app/pages/Section2Page.scala
- app/pages/Section3Page.scala
- app/pages/Section4Page.scala
- app/pages/checkEligibility/InEligiblePage.scala
- app/views/Index.scala.html
- app/views/components/h1.scala.html
- build.sbt
- conf/app.routes
- conf/application.conf
- conf/messages.cy
- conf/messages.en
- test/generators/UserAnswersGenerator.scala
- test/navigation/CharityInformationNavigatorSpec.scala
- test/views/IndexViewSpec.scala
- test/views/charityInformation/CharityUKAddressViewSpec.scala
> [DDCE-407]:Build skeleton Task List page

- conf/messages.cy
- conf/messages.en
> DDCE-567:Removed full stops at the end of hint texts

- app/controllers/IndexController.scala
- app/controllers/regulatorsAndDocuments/IsCharityRegulatorController.scala
- app/forms/regulatorsAndDocuments/IsCharityRegulatorFormProvider.scala
- app/navigation/RegulatorsAndDocumentsNavigator.scala
- app/pages/regulatorsAndDocuments/IsCharityRegulatorPage.scala
- app/views/Index.scala.html
- app/views/regulatorsAndDocuments/IsCharityRegulatorView.scala.html
- conf/app.routes
- conf/messages.cy
- conf/messages.en
- conf/regulatorsAndDocuments.routes
- test/controllers/regulatorsAndDocuments/IsCharityRegulatorControllerSpec.scala
- test/forms/charityInformation/IsCharityOfficialAddressInUKFormProviderSpec.scala
- test/forms/regulatorsAndDocuments/IsCharityRegulatorFormProviderSpec.scala
- test/navigation/FakeNavigators.scala
- test/navigation/RegulatorsAndDocumentsNavigatorSpec.scala
- test/pages/regulatorsAndDocuments/IsCharityRegulatorPageSpec.scala
- test/views/regulatorsAndDocuments/IsCharityRegulatorViewSpec.scala
> [DDCE-512]:P1 - Is your charity registered with a charity regulator?

- app/controllers/regulatorsAndDocuments/CharityRegulatorController.scala
- app/forms/regulatorsAndDocuments/CharityRegulatorFormProvider.scala
- app/models/regulators/CharityRegulator.scala
- app/navigation/RegulatorsAndDocumentsNavigator.scala
- app/pages/regulatorsAndDocuments/CharityRegulatorPage.scala
- app/views/regulatorsAndDocuments/CharityRegulatorView.scala.html
- conf/messages.cy
- conf/messages.en
- conf/regulatorsAndDocuments.routes
- test/controllers/regulatorsAndDocuments/CharityRegulatorControllerSpec.scala
- test/forms/regulatorsAndDocuments/CharityRegulatorFormProviderSpec.scala
- test/generators/Generators.scala
- test/generators/ModelGenerators.scala
- test/models/regulators/CharityRegulatorSpec.scala
- test/navigation/RegulatorsAndDocumentsNavigatorSpec.scala
- test/pages/regulatorsAndDocuments/CharityRegulatorPageSpec.scala
- test/views/regulatorsAndDocuments/CharityRegulatorViewSpec.scala
> [DDCE-514]:2 P2A - Who is your charity's regulator?

- app/controllers/regulatorsAndDocuments/ScottishRegulatorRegNumberController.scala
- app/forms/regulatorsAndDocuments/ScottishRegulatorRegNumberFormProvider.scala
- app/navigation/RegulatorsAndDocumentsNavigator.scala
- app/pages/regulatorsAndDocuments/ScottishRegulatorRegNumberPage.scala
- app/views/regulatorsAndDocuments/ScottishRegulatorRegNumberView.scala.html
- conf/messages.cy
- conf/messages.en
- conf/regulatorsAndDocuments.routes
- test/controllers/regulatorsAndDocuments/ScottishRegulatorRegNumberControllerSpec.scala
- test/forms/regulatorsAndDocuments/ScottishRegulatorRegNumberFormProviderSpec.scala
- test/navigation/RegulatorsAndDocumentsNavigatorSpec.scala
- test/pages/regulatorsAndDocuments/ScottishRegulatorRegNumberPageSpec.scala
- test/views/regulatorsAndDocuments/ScottishRegulatorRegNumberViewSpec.scala
> DDCE-518 CharityScottishRegulatorRegistrationNumber page

- app/controllers/regulatorsAndDocuments/SelectWhyNoRegulatorController.scala
- app/forms/regulatorsAndDocuments/SelectWhyNoRegulatorFormProvider.scala
- app/models/regulators/SelectWhyNoRegulator.scala
- app/navigation/RegulatorsAndDocumentsNavigator.scala
- app/pages/regulatorsAndDocuments/SelectWhyNoRegulatorPage.scala
- app/views/regulatorsAndDocuments/SelectWhyNoRegulatorView.scala.html
- conf/messages.cy
- conf/messages.en
- conf/regulatorsAndDocuments.routes
- test/controllers/regulatorsAndDocuments/SelectWhyNoRegulatorControllerSpec.scala
- test/forms/regulatorsAndDocuments/SelectWhyNoRegulatorFormProviderSpec.scala
- test/models/regulators/SelectWhyNoRegulatorSpec.scala
- test/navigation/RegulatorsAndDocumentsNavigatorSpec.scala
- test/pages/regulatorsAndDocuments/SelectWhyNoRegulatorPageSpec.scala
- test/views/regulatorsAndDocuments/SelectWhyNoRegulatorViewSpec.scala
> [DDCE-515]:2 P2B - Why have you not registered with a charity regulator?

- app/controllers/regulatorsAndDocuments/CharityRegulatorController.scala
- app/models/regulators/CharityRegulator.scala
- app/navigation/RegulatorsAndDocumentsNavigator.scala
- test/controllers/regulatorsAndDocuments/CharityRegulatorControllerSpec.scala
- test/navigation/RegulatorsAndDocumentsNavigatorSpec.scala
> DDCE-600: §2 P2A Journeys - Who is your charity's regulator?

- app/navigation/RegulatorsAndDocumentsNavigator.scala
- test/navigation/RegulatorsAndDocumentsNavigatorSpec.scala
> [DDCE-671]:P7 - Implement Routing for Summary Page

- app/config/FrontendAppConfig.scala
- app/controllers/SignOutController.scala
- app/views/Index.scala.html
- app/views/checkEligibility/InEligibleView.scala.html
- app/views/checkEligibility/IncorrectDetailsView.scala.html
- app/views/checkEligibility/IsEligibleAccountView.scala.html
- app/views/checkEligibility/IsEligibleLocationOtherView.scala.html
- app/views/checkEligibility/IsEligibleLocationView.scala.html
- app/views/checkEligibility/IsEligiblePurposeView.scala.html
- app/views/errors/SessionExpiredView.scala.html
- app/views/templates/GovukLayoutWrapper.scala.html
- conf/app.routes
- conf/application.conf
- conf/messages.cy
- conf/messages.en
- test/controllers/SignOutControllerSpec.scala
> DDCE-594: signout without feedback and service home changes

- app/controllers/regulatorsAndDocuments/WhyNotRegisteredWithCharityController.scala
- app/forms/regulatorsAndDocuments/WhyNotRegisteredWithCharityFormProvider.scala
- app/navigation/RegulatorsAndDocumentsNavigator.scala
- app/pages/regulatorsAndDocuments/WhyNotRegisteredWithCharityPage.scala
- app/views/components/inputCharacterCount.scala.html
- app/views/components/inputTextArea.scala.html
- app/views/regulatorsAndDocuments/WhyNotRegisteredWithCharityView.scala.html
- conf/messages.cy
- conf/messages.en
- conf/regulatorsAndDocuments.routes
- test/controllers/regulatorsAndDocuments/WhyNotRegisteredWithCharityControllerSpec.scala
- test/forms/regulatorsAndDocuments/WhyNotRegisteredWithCharityFormProviderSpec.scala
- test/navigation/RegulatorsAndDocumentsNavigatorSpec.scala
- test/pages/regulatorsAndDocuments/WhyNotRegisteredWithCharityPageSpec.scala
- test/views/behaviours/TextAreaViewBehaviours.scala
- test/views/behaviours/ViewBehaviours.scala
- test/views/regulatorsAndDocuments/WhyNotRegisteredWithCharityViewSpec.scala
##New feature 
why your charity is not registered with charity regulator
> DDCE-516 why your charity is not registered with charity regulator

- app/forms/regulatorsAndDocuments/NIRegulatorRegNumberFormProvider.scala
- conf/messages.cy
- test/forms/regulatorsAndDocuments/NIRegulatorRegNumberFormProviderSpec.scala
##Bug fix 
Updated nI welsh and form provider message keys.
> KeyFix1: Changed form provider message keys to match current pattern

- app/navigation/RegulatorsAndDocumentsNavigator.scala
- app/viewmodels/regulatorsAndDocuments/GoverningDocumentSummaryHelper.scala
- conf/messages.cy
- conf/messages.en
- test/navigation/RegulatorsAndDocumentsNavigatorSpec.scala
- test/viewModels/regulatorsAndDocuments/GoverningDocumentSummaryHelperSpec.scala
> [DDCE-603]:§2 P7 Journeys 3-6 - Check your charity’s regulator details

- app/controllers/IndexController.scala
- app/controllers/charityInformation/CharityContactDetailsController.scala
- app/controllers/charityInformation/CharityNameController.scala
- app/controllers/charityInformation/CharityUKAddressController.scala
- app/controllers/charityInformation/IsCharityOfficialAddressInUKController.scala
- app/controllers/regulatorsAndDocuments/CharityCommissionRegistrationNumberController.scala
- app/controllers/regulatorsAndDocuments/CharityOtherRegulatorDetailsController.scala
- app/controllers/regulatorsAndDocuments/CharityRegulatorController.scala
- app/controllers/regulatorsAndDocuments/GoverningDocumentSummaryController.scala
- app/controllers/regulatorsAndDocuments/IsCharityRegulatorController.scala
- app/controllers/regulatorsAndDocuments/NIRegulatorRegNumberController.scala
- app/controllers/regulatorsAndDocuments/ScottishRegulatorRegNumberController.scala
- app/controllers/regulatorsAndDocuments/SelectWhyNoRegulatorController.scala
- app/controllers/regulatorsAndDocuments/WhyNotRegisteredWithCharityController.scala
- app/models/UserAnswers.scala
- app/navigation/RegulatorsAndDocumentsNavigator.scala
- app/pages/regulatorsAndDocuments/CharityRegulatorPage.scala
- app/pages/sections/Section1Page.scala
- app/pages/sections/Section2Page.scala
- app/pages/sections/Section3Page.scala
- app/pages/sections/Section4Page.scala
- app/queries/Query.scala
- build.sbt
- test/navigation/RegulatorsAndDocumentsNavigatorSpec.scala
- test/pages/regulatorsAndDocuments/CharityRegulatorPageSpec.scala
> DDCE-605: navigation and data reset changes

- app/controllers/regulatorsAndDocuments/IsCharityRegulatorController.scala
- app/navigation/RegulatorsAndDocumentsNavigator.scala
- app/pages/regulatorsAndDocuments/IsCharityRegulatorPage.scala
- test/navigation/RegulatorsAndDocumentsNavigatorSpec.scala
- test/pages/regulatorsAndDocuments/IsCharityRegulatorPageSpec.scala
##New feature
Implemented cleardown, logic and check route navigation for journey 1 
https://jira.tools.tax.service.gov.uk/browse/DDCE-604
> DDCE-602: Check mode routes and cleardown for journey 1

- app/views/charityInformation/CharityNameView.scala.html
> DDCE-522:Fixed duplicate id error on charity name page

- app/config/FrontendAppConfig.scala
- app/connectors/addressLookup/AddressLookupConfiguration.scala
- app/connectors/addressLookup/AddressLookupConnector.scala
- app/connectors/addressLookup/httpParsers/AddressLookupInitializationHttpParser.scala
- app/connectors/addressLookup/httpParsers/ConfirmedAddressHttpParser.scala
- app/connectors/addressLookup/httpParsers/ErrorResponse.scala
- app/controllers/addressLookup/CharityInformationAddressLookupController.scala
- app/models/addressLookup/AddressLookupConfigurationModel.scala
- app/models/addressLookup/AddressLookupConfirmConfigModel.scala
- app/models/addressLookup/AddressLookupConfirmTimeoutModel.scala
- app/models/addressLookup/AddressLookupLanguageModel.scala
- app/models/addressLookup/AddressLookupOptionsModel.scala
- app/models/addressLookup/AddressLookupSelectConfigModel.scala
- app/models/addressLookup/AddressModel.scala
- app/models/addressLookup/package.scala
- app/navigation/CharityInformationNavigator.scala
- app/pages/addressLookup/CharityInformationAddressLookupPage.scala
- app/utils/MessageOption.scala
- conf/address.routes
- conf/app.routes
- conf/application.conf
- conf/messages.cy
- conf/messages.en
- test/assets/constants/ConfirmedAddressConstants.scala
- test/connectors/WireMockHelper.scala
- test/connectors/addressLookup/AddressLookupConnectorSpec.scala
- test/connectors/addressLookup/httpParsers/AddressLookupInitializationHttpParserSpec.scala
- test/connectors/addressLookup/httpParsers/ConfirmedAddressHttpParserSpec.scala
- test/controllers/addressLookup/CharityInformationAddressLookupControllerSpec.scala
- test/navigation/CharityInformationNavigatorSpec.scala
> [DDCE-613]:§1 P3A.1-P3C Official Address Lookup

- app/viewmodels/regulatorsAndDocuments/GoverningDocumentSummaryHelper.scala
- test/controllers/regulatorsAndDocuments/IsApprovedGoverningDocumentControllerSpec.scala
- test/navigation/DocumentsNavigatorSpec.scala
- test/viewModels/regulatorsAndDocuments/GoverningDocumentSummaryHelperSpec.scala
> DDCE-668 modified test case

- app/connectors/addressLookup/httpParsers/AddressLookupInitializationHttpParser.scala
> [DDCE-613]: Address lookup- Modified logger level to error

- app/controllers/regulatorsAndDocuments/IsApprovedGoverningDocumentController.scala
> [DDCE-613]: Address lookup- Code refactor

- app/controllers/charityInformation/CharityInformationSummaryController.scala
- app/navigation/CharityInformationNavigator.scala
- app/pages/charityInformation/CharityInformationSummaryPage.scala
- app/viewmodels/charityInformation/CharityInformationSummaryHelper.scala
- conf/charityInformation.routes
- conf/messages.cy
- conf/messages.en
- test/controllers/charityInformation/CharityInformationSummaryControllerSpec.scala
- test/navigation/CharityInformationNavigatorSpec.scala
- test/viewModels/regulatorsAndDocuments/CharityInformationSummaryHelperSpec.scala
> DDCE-448:§1 P6 - Check your charity's contact details

- app/controllers/operationsAndFunds/PublicBenefitsController.scala
- app/forms/operationsAndFunds/PublicBenefitsFormProvider.scala
- app/navigation/OperationsAndFundsNavigator.scala
- app/pages/operationsAndFunds/PublicBenefitsPage.scala
- app/views/operationsAndFunds/PublicBenefitsView.scala.html
- conf/app.routes
- conf/messages.cy
- conf/messages.en
- conf/operationsAndFunds.routes
- test/controllers/operationsAndFunds/PublicBenefitsControllerSpec.scala
- test/forms/operationsAndFunds/PublicBenefitsFormProviderSpec.scala
- test/navigation/FakeNavigators.scala
- test/navigation/OperationsAndFundsNavigatorSpec.scala
- test/pages/charityInformation/CharityInformationSummaryPageSpec.scala
- test/pages/operationsAndFunds/PublicBenefitsPageSpec.scala
- test/views/operationsAndFunds/PublicFundsViewSpec.scala
> [DDCE-682]:§4 P3 - How does your charity benefit the public?

- app/controllers/addressLookup/CharityInformationAddressLookupController.scala
- app/controllers/operationsAndFunds/FundRaisingController.scala
- app/forms/operationsAndFunds/FundRaisingFormProvider.scala
- app/models/operations/FundRaisingOptions.scala
- app/navigation/FundRaisingNavigator.scala
- app/pages/operationsAndFunds/FundRaisingPage.scala
- app/pages/sections/Section5Page.scala
- app/views/Index.scala.html
- app/views/operationsAndFunds/FundRaisingView.scala.html
- conf/app.routes
- conf/messages.cy
- conf/messages.en
- conf/operationsAndFunds.routes
- project/AppDependencies.scala
- test/controllers/addressLookup/CharityInformationAddressLookupControllerSpec.scala
- test/controllers/operationsAndFunds/FundRaisingControllerSpec.scala
- test/forms/operationsAndFunds/FundRaisingFormProviderSpec.scala
- test/navigation/FakeNavigators.scala
- test/navigation/FundRaisingNavigatorSpec.scala
- test/pages/operationsAndFunds/FundRaisingPageSpec.scala
- test/views/operationsAndFunds/FundRaisingViewSpec.scala
> DDCE-684: page changes for - How will your charity raise funds

- app/controllers/operationsAndFunds/CharitablePurposesController.scala
- app/forms/operationsAndFunds/CharitablePurposesFormProvider.scala
- app/models/operations/CharitablePurposes.scala
- app/navigation/ObjectivesNavigator.scala
- app/pages/operationsAndFunds/CharitablePurposesPage.scala
- app/views/operationsAndFunds/CharitablePurposesView.scala.html
- conf/messages.cy
- conf/messages.en
- conf/operationsAndFunds.routes
- test/controllers/operationsAndFunds/CharitablePurposesControllerSpec.scala
- test/forms/operationsAndFunds/CharitablePurposesFormProviderSpec.scala
- test/models/operations/CharitablePurposesSpec.scala
- test/navigation/ObjectivesNavigatorSpec.scala
- test/pages/operationsAndFunds/CharitablePurposesPageSpec.scala
- test/views/operationsAndFunds/CharitablePurposesViewSpec.scala
> DDCE-680:charitable purposes

- app/assets/stylesheets/application.scss
- app/config/FrontendAppConfig.scala
- app/views/checkEligibility/InEligibleView.scala.html
- app/views/checkEligibility/IncorrectDetailsView.scala.html
- app/views/checkEligibility/IsEligibleAccountView.scala.html
- app/views/checkEligibility/IsEligibleLocationOtherView.scala.html
- app/views/checkEligibility/IsEligibleLocationView.scala.html
- app/views/checkEligibility/IsEligiblePurposeView.scala.html
- app/views/components/phaseBanner.scala.html
- app/views/errors/SessionExpiredView.scala.html
- app/views/templates/GovukLayoutWrapper.scala.html
- conf/application.conf
- conf/prod.routes
- test/views/components/PhaseBannerSpec.scala
> DDCE-609: Amend service URL

- app/controllers/operationsAndFunds/OperatingLocationController.scala
- app/forms/operationsAndFunds/OperatingLocationFormProvider.scala
- app/models/operations/OperatingLocationOptions.scala
- app/navigation/FundRaisingNavigator.scala
- app/pages/operationsAndFunds/OperatingLocationPage.scala
- app/views/operationsAndFunds/OperatingLocationView.scala.html
- conf/messages.cy
- conf/messages.en
- conf/operationsAndFunds.routes
- test/controllers/operationsAndFunds/OperatingLocationControllerSpec.scala
- test/forms/operationsAndFunds/OperatingLocationFormProviderSpec.scala
- test/navigation/FundRaisingNavigatorSpec.scala
- test/pages/operationsAndFunds/OperatingLocationPageSpec.scala
- test/views/operationsAndFunds/OperatingLocationViewSpec.scala
> [DDCE-685]:§5 P2 - Where does your charity operate?

- app/controllers/operationsAndFunds/IsFinancialAccountsController.scala
- app/forms/operationsAndFunds/IsFinancialAccountsFormProvider.scala
- app/navigation/FundRaisingNavigator.scala
- app/pages/operationsAndFunds/IsFinancialAccountsPage.scala
- app/views/operationsAndFunds/IsFinancialAccountsView.scala.html
- conf/messages.cy
- conf/messages.en
- conf/operationsAndFunds.routes
- test/controllers/operationsAndFunds/IsFinancialAccountsControllerSpec.scala
- test/forms/operationsAndFunds/IsFinancialAccountsFormProviderSpec.scala
- test/navigation/FundRaisingNavigatorSpec.scala
- test/pages/operationsAndFunds/IsFinancialAccountsPageSpec.scala
- test/views/operationsAndFunds/IsFinancialAccountsViewSpec.scala
> DDCE-686:Charity financial accounts page creation

- app/controllers/operationsAndFunds/CharityObjectivesSummaryController.scala
- app/navigation/ObjectivesNavigator.scala
- app/pages/operationsAndFunds/CharityObjectivesSummaryPage.scala
- app/viewmodels/operationsAndFunds/CharityObjectivesSummaryHelper.scala
- conf/messages.cy
- conf/messages.en
- conf/operationsAndFunds.routes
- test/controllers/operationsAndFunds/CharityObjectivesSummaryControllerSpec.scala
- test/navigation/ObjectivesNavigatorSpec.scala
- test/pages/operationsAndFunds/CharityObjectivesSummaryPageSpec.scala
- test/viewModels/charityInformation/CharityInformationSummaryHelperSpec.scala
- test/viewModels/operationsAndFunds/CharityObjectivesSummaryHelperSpec.scala
##New feature
DDCE-683: Summary page for Section 4: Charity Objectives
> DDCE-683: Added summary page for section 4 : Charitable objectives

- app/controllers/IndexController.scala
- app/models/TaskListSection.scala
- app/views/Index.scala.html
- conf/messages.cy
- conf/messages.en
- test/views/IndexViewSpec.scala
##New feature
Verification of Section 4 journey including task list status update.
> DDCE-714: Section 4 navigation with updated index status functionality

- app/controllers/operationsAndFunds/OperationsFundsSummaryController.scala
- app/navigation/FundRaisingNavigator.scala
- app/pages/operationsAndFunds/OperationsFundsSummaryPage.scala
- app/viewmodels/CheckYourAnswersHelper.scala
- app/viewmodels/charityInformation/CharityInformationSummaryHelper.scala
- app/viewmodels/operationsAndFunds/CharityObjectivesSummaryHelper.scala
- app/viewmodels/operationsAndFunds/OperationsFundsSummaryHelper.scala
- app/viewmodels/regulatorsAndDocuments/GoverningDocumentSummaryHelper.scala
- app/viewmodels/regulatorsAndDocuments/RegulatorsSummaryHelper.scala
- conf/messages.cy
- conf/messages.en
- conf/operationsAndFunds.routes
- test/controllers/operationsAndFunds/CharitableObjectivesControllerSpec.scala
- test/controllers/operationsAndFunds/CharitablePurposesControllerSpec.scala
- test/controllers/operationsAndFunds/OperationsFundsSummaryControllerSpec.scala
- test/controllers/operationsAndFunds/PublicBenefitsControllerSpec.scala
- test/navigation/FakeNavigators.scala
- test/navigation/FundRaisingNavigatorSpec.scala
- test/pages/operationsAndFunds/OperationsFundsSummaryPageSpec.scala
- test/viewModels/charityInformation/CharityInformationSummaryHelperSpec.scala
- test/viewModels/operationsAndFunds/OperationsFundsSummaryHelperSpec.scala
- test/viewModels/regulatorsAndDocuments/GoverningDocumentSummaryHelperSpec.scala
- test/viewModels/regulatorsAndDocuments/RegulatorsSummaryHelperSpec.scala
> [DDCE-723]:§5 P8 - Check your charity’s operations and funds details

- app/viewmodels/regulatorsAndDocuments/RegulatorsSummaryHelper.scala
- conf/messages.cy
- conf/messages.en
- test/viewModels/regulatorsAndDocuments/RegulatorsSummaryHelperSpec.scala
> DDCE-790  Update 'Other charity regulator' row in summary page

- app/controllers/IndexController.scala
- app/controllers/operationsAndFunds/BankDetailsController.scala
- app/forms/mappings/Constraints.scala
- app/forms/operationsAndFunds/BankDetailsFormProvider.scala
- app/models/OperationAndFunds.scala
- app/navigation/BankDetailsNavigator.scala
- app/pages/operationsAndFunds/BankDetailsPage.scala
- app/pages/sections/Section6Page.scala
- app/views/Index.scala.html
- app/views/components/warning.scala.html
- app/views/operationsAndFunds/BankDetailsView.scala.html
- conf/messages.cy
- conf/messages.en
- conf/operationsAndFunds.routes
- test/controllers/operationsAndFunds/BankDetailsControllerSpec.scala
- test/forms/operationsAndFunds/BankDetailsFormProviderSpec.scala
- test/navigation/BankDetailsNavigatorSpec.scala
- test/navigation/FakeNavigators.scala
- test/pages/operationsAndFunds/BankDetailsPageSpec.scala
- test/views/IndexViewSpec.scala
- test/views/behaviours/ViewBehaviours.scala
- test/views/operationsAndFunds/BankDetailsViewSpec.scala
> DDCE-754: changes for What are your charity’s bank account details page

- app/models/OperationAndFunds.scala
- test/models/OperationAndFundsSpec.scala
> DDCE-754: Sortcode and AccountNumber numeric formats

- app/controllers/operationsAndFunds/BankDetailsSummaryController.scala
- app/navigation/BankDetailsNavigator.scala
- app/pages/operationsAndFunds/BankDetailsSummaryPage.scala
- app/viewmodels/operationsAndFunds/BankDetailsSummaryHelper.scala
- conf/messages.cy
- conf/messages.en
- conf/operationsAndFunds.routes
- test/controllers/operationsAndFunds/BankDetailsSummaryControllerSpec.scala
- test/navigation/BankDetailsNavigatorSpec.scala
- test/pages/operationsAndFunds/BankDetailsSummaryPageSpec.scala
- test/viewModels/operationsAndFunds/BankDetailsSummaryHelperSpec.scala
> [DDCE-760]:§6 P2 - Check your charity’s bank details

- app/views/templates/GovukLayoutWrapper.scala.html
- project/AppDependencies.scala
##Bug fix 
Correct 'Get help with this page' link.
> DDCE-608new:Correct 'Get help with this page' link

- app/controllers/IndexController.scala
- test/controllers/IndexControllerSpec.scala
> DDCE-762: Changes to bank details navigations

- app/controllers/DeadEndController.scala
- app/navigation/CharityInformationNavigator.scala
- app/navigation/DocumentsNavigator.scala
- app/navigation/FundRaisingNavigator.scala
- app/navigation/ObjectivesNavigator.scala
- app/pages/DeadEndPage.scala
- app/viewmodels/operationsAndFunds/OperationsFundsSummaryHelper.scala
- app/viewmodels/regulatorsAndDocuments/GoverningDocumentSummaryHelper.scala
- app/views/DeadEndView.scala.html
- app/views/components/linkAsButton.scala.html
- conf/app.routes
- conf/messages.cy
- conf/messages.en
- test/controllers/DeadEndControllerSpec.scala
- test/navigation/CharityInformationNavigatorSpec.scala
- test/navigation/DocumentsNavigatorSpec.scala
- test/navigation/FundRaisingNavigatorSpec.scala
- test/navigation/ObjectivesNavigatorSpec.scala
- test/pages/DeadEndPageSpec.scala
- test/viewModels/operationsAndFunds/OperationsFundsSummaryHelperSpec.scala
- test/viewModels/regulatorsAndDocuments/GoverningDocumentSummaryHelperSpec.scala
- test/views/DeadEndViewSpec.scala
> DDCE-789:DeadEnd Page creation

- app/controllers/IndexController.scala
- app/controllers/authorisedOfficials/CharityAuthorisedOfficialsController.scala
- app/navigation/AuthorisedOfficialsNavigator.scala
- app/pages/authorisedOfficials/CharityAuthorisedOfficialsPage.scala
- app/pages/sections/Section7Page.scala
- app/views/TaskList.scala.html
- app/views/authorisedOfficials/CharityAuthorisedOfficialsView.scala.html
- conf/messages.cy
- conf/messages.en
- conf/officialsAndNominees.routes
- test/controllers/authorisedOfficials/CharityAuthorisedOfficialsControllerSpec.scala
- test/navigation/AuthorisedOfficialsNavigatorSpec.scala
- test/pages/authorisedOfficials/CharityAuthorisedOfficialsPageSpec.scala
- test/views/TaskListViewSpec.scala
- test/views/authorisedOfficials/CharityAuthorisedOfficialsViewSpec.scala
##New feature
Charity’s authorised officials
> Ddce 763 Charity’s authorised officials

- app/controllers/LocalBaseController.scala
- app/controllers/authorisedOfficials/AuthorisedOfficialsDOBController.scala
- app/forms/authorisedOfficials/AuthorisedOfficialsDOBFormProvider.scala
- app/models/AuthorisedOfficials.scala
- app/navigation/AuthorisedOfficialsNavigator.scala
- app/pages/authorisedOfficials/AuthorisedOfficialsDOBPage.scala
- app/views/authorisedOfficials/AuthorisedOfficialsDOBView.scala.html
- conf/messages.cy
- conf/messages.en
- conf/officialsAndNominees.routes
- test/controllers/LocalBaseControllerSpec.scala
- test/controllers/authorisedOfficials/AuthorisedOfficialsDOBControllerSpec.scala
- test/forms/authorisedOfficials/AuthorisedOfficialsDOBFormProviderSpec.scala
- test/models/AuthorisedOfficialsSpec.scala
- test/navigation/AuthorisedOfficialsNavigatorSpec.scala
- test/pages/authorisedOfficials/AuthorisedOfficialsDOBPageSpec.scala
- test/views/authorisedOfficials/AuthorisedOfficialsDOBViewSpec.scala
> DDCE-765:§7 P3 - What is [Full name]'s date of birth?

- app/controllers/authorisedOfficials/AuthorisedOfficialsNameController.scala
- app/controllers/authorisedOfficials/AuthorisedOfficialsPhoneNumberController.scala
- app/forms/authorisedOfficials/AuthorisedOfficialsPhoneNumberFormProvider.scala
- app/forms/charityInformation/CharityContactDetailsFormProvider.scala
- app/models/AuthorisedOfficials.scala
- app/navigation/AuthorisedOfficialsNavigator.scala
- app/pages/authorisedOfficials/AuthorisedOfficialsPhoneNumberPage.scala
- app/views/authorisedOfficials/AuthorisedOfficialsPhoneNumberView.scala.html
- conf/messages.cy
- conf/messages.en
- conf/officialsAndNominees.routes
- test/controllers/authorisedOfficials/AuthorisedOfficialsPhoneNumberControllerSpec.scala
- test/forms/authorisedOfficials/AuthorisedOfficialsPhoneNumberFormProviderSpec.scala
- test/models/AuthorisedOfficialsSpec.scala
- test/navigation/AuthorisedOfficialsNavigatorSpec.scala
- test/pages/authorisedOfficials/AuthorisedOfficialsPhoneNumberPageSpec.scala
- test/views/authorisedOfficials/AuthorisedOfficialsPhoneNumberViewSpec.scala
##New feature (delete as appropriate)
To add the authorised officials phone number to the journey.
>  DDCE-773: Added Authorised official's phone number page

- app/models/WithOrder.scala
- app/models/operations/CharitablePurposes.scala
- app/models/operations/FundRaisingOptions.scala
- app/models/operations/OperatingLocationOptions.scala
- app/models/regulators/CharityRegulator.scala
- app/viewmodels/CheckYourAnswersHelper.scala
- test/models/WithOrderSpec.scala
- test/models/operations/CharitablePurposesSpec.scala
- test/models/regulators/CharityRegulatorSpec.scala
- test/viewModels/operationsAndFunds/CharityObjectivesSummaryHelperSpec.scala
- test/viewModels/operationsAndFunds/OperationsFundsSummaryHelperSpec.scala
> DDCE-817: Correction - Check your charity’s objectives details

- app/controllers/authorisedOfficials/IsAuthorisedOfficialPositionController.scala
- app/forms/authorisedOfficials/IsAuthorisedOfficialPositionFormProvider.scala
- app/navigation/AuthorisedOfficialsNavigator.scala
- app/pages/authorisedOfficials/IsAuthorisedOfficialPositionPage.scala
- app/views/authorisedOfficials/IsAuthorisedOfficialPositionView.scala.html
- conf/messages.cy
- conf/messages.en
- conf/officialsAndNominees.routes
- test/controllers/authorisedOfficials/IsAuthorisedOfficialPositionControllerSpec.scala
- test/forms/authorisedOfficials/IsAuthorisedOfficialPositionFormProviderSpec.scala
- test/navigation/AuthorisedOfficialsNavigatorSpec.scala
- test/pages/authorisedOfficials/IsAuthorisedOfficialPositionPageSpec.scala
- test/views/authorisedOfficials/IsAuthorisedOfficialPositionViewSpec.scala
> DDCE-775:National Insurance number Question page

- app/controllers/addressLookup/AuthorisedOfficialsAddressLookupController.scala
- app/controllers/authorisedOfficials/AuthorisedOfficialsDOBController.scala
- app/controllers/authorisedOfficials/AuthorisedOfficialsPhoneNumberController.scala
- app/models/addressLookup/AddressLookupLanguageModel.scala
- app/navigation/AuthorisedOfficialsNavigator.scala
- app/pages/addressLookup/AuthorisedOfficialAddressLookupPage.scala
- conf/address.routes
- conf/messages.cy
- conf/messages.en
- test/controllers/addressLookup/AuthroisedOfficialsAddressLookupControllerSpec.scala
- test/navigation/AuthorisedOfficialsNavigatorSpec.scala
- test/pages/addressLookup/AuthorisedOfficialsAddressPageSpec.scala
- test/pages/addressLookup/CharityOfficialAddressLookupPageSpec.scala
> DDCE-792: authorised official address lookup changes

- conf/messages.cy
- conf/messages.en
> removed service name from address lookup title messages

- README.md
- app/controllers/authorisedOfficials/AuthorisedOfficialPreviousAddressController.scala
- app/controllers/authorisedOfficials/IsAuthorisedOfficialPositionController.scala
- app/forms/authorisedOfficials/AuthorisedOfficialPreviousAddressFormProvider.scala
- app/navigation/AuthorisedOfficialsNavigator.scala
- app/pages/authorisedOfficials/AuthorisedOfficialPreviousAddressPage.scala
- app/views/authorisedOfficials/AuthorisedOfficialPreviousAddressView.scala.html
- conf/messages.cy
- conf/messages.en
- conf/officialsAndNominees.routes
- test/controllers/authorisedOfficials/AuthorisedOfficialPreviousAddressControllerSpec.scala
- test/forms/authorisedOfficials/AuthorisedOfficialPreviousAddressFormProviderSpec.scala
- test/navigation/AuthorisedOfficialsNavigatorSpec.scala
- test/pages/authorisedOfficials/AuthorisedOfficialPreviousAddressPageSpec.scala
- test/views/authorisedOfficials/AuthorisedOfficialPreviousAddressViewSpec.scala
##New feature (delete as appropriate)
Added Authorised Official Previous Address page
> DDCE-793: Added Authorised Official Previous Address Query page

- app/controllers/authorisedOfficials/AuthorisedOfficialsNINOController.scala
- app/forms/authorisedOfficials/AuthorisedOfficialsNINOFormProvider.scala
- app/models/AuthOfficials/AuthorisedOfficialsPosition.scala
- app/utils/ImplicitDateFormatter.scala
- app/viewmodels/operationsAndFunds/OperationsFundsSummaryHelper.scala
- project/AppDependencies.scala
- test/utils/ImplicitDateFormatterSpec.scala
- test/viewModels/operationsAndFunds/OperationsFundsSummaryHelperSpec.scala
> DDCE-844 - welsh translation changes for dates

- app/controllers/authorisedOfficials/IsAddAnotherAuthorisedOfficialController.scala
- app/forms/authorisedOfficials/IsAddAnotherAuthorisedOfficialFormProvider.scala
- app/navigation/AuthorisedOfficialsNavigator.scala
- app/pages/authorisedOfficials/IsAddAnotherAuthorisedOfficialPage.scala
- app/views/authorisedOfficials/IsAddAnotherAuthorisedOfficialView.scala.html
- conf/messages.cy
- conf/messages.en
- conf/officialsAndNominees.routes
- test/controllers/authorisedOfficials/IsAddAnotherAuthorisedOfficialControllerSpec.scala
- test/forms/authorisedOfficials/IsAddAnotherAuthorisedOfficialFormProviderSpec.scala
- test/navigation/AuthorisedOfficialsNavigatorSpec.scala
- test/pages/authorisedOfficials/IsAddAnotherAuthorisedOfficialPageSpec.scala
- test/views/authorisedOfficials/IsAddAnotherAuthorisedOfficialViewSpec.scala
> DDCE-795:Add another authorised official question page

- app/views/checkEligibility/IsEligibleLocationOtherView.scala.html
- app/views/checkEligibility/IsEligiblePurposeView.scala.html
- app/views/regulatorsAndDocuments/CharityCommissionRegistrationNumberView.scala.html
- app/views/regulatorsAndDocuments/CharityOtherRegulatorDetailsView.scala.html
- app/views/regulatorsAndDocuments/IsCharityRegulatorView.scala.html
- app/views/regulatorsAndDocuments/NIRegulatorRegNumberView.scala.html
- app/views/regulatorsAndDocuments/ScottishRegulatorRegNumberView.scala.html
- conf/messages.cy
- conf/messages.en
- conf/officialsAndNominees.routes
- test/views/checkEligibility/IsEligibleLocationOtherViewSpec.scala
- test/views/checkEligibility/IsEligiblePurposeViewSpec.scala
> [DDCE-851]:Replace all 'Details' components with paragraph text under H1

- conf/messages.cy
- conf/messages.en
> DDCE-850: Correct H1 to 'What are your charity's regulators'

- app/controllers/nominees/IsAuthoriseNomineeController.scala
- app/forms/nominees/IsAuthoriseNomineeFormProvider.scala
- app/navigation/NomineesNavigator.scala
- app/pages/nominees/IsAuthoriseNomineePage.scala
- app/views/nominees/IsAuthoriseNomineeView.scala.html
- conf/messages.cy
- conf/messages.en
- conf/officialsAndNominees.routes
- test/controllers/nominees/IsAuthoriseNomineeControllerSpec.scala
- test/forms/nominees/IsAuthoriseNomineeFormProviderSpec.scala
- test/navigation/FakeNavigators.scala
- test/navigation/NomineesNavigatorSpec.scala
- test/pages/nominees/IsAuthoriseNomineePageSpec.scala
- test/views/nominees/CharityNomineeViewSpec.scala
- test/views/nominees/IsAuthoriseNomineeViewSpec.scala
> DDCE-778:Initial commit for authorise a nominee question page

- app/controllers/authorisedOfficials/AddedOneAuthorisedOfficialController.scala
- app/navigation/AuthorisedOfficialsNavigator.scala
- app/pages/authorisedOfficials/AddedOneAuthorisedOfficialPage.scala
- app/viewmodels/authorisedOfficials/AddedOneAuthorisedOfficialHelper.scala
- app/viewmodels/regulatorsAndDocuments/RegulatorsSummaryHelper.scala
- app/views/authorisedOfficials/AddedOneAuthorisedOfficialView.scala.html
- conf/messages.cy
- conf/messages.en
- conf/officialsAndNominees.routes
- test/controllers/authorisedOfficials/AddedOneAuthorisedOfficialControllerSpec.scala
- test/navigation/AuthorisedOfficialsNavigatorSpec.scala
- test/navigation/EligibilityNavigatorSpec.scala
- test/pages/authorisedOfficials/AddedOneAuthorisedOfficialPageSpec.scala
- test/viewModels/authorisedOfficials/AddedOneAuthorisedOfficialHelperSpec.scala
- test/viewModels/regulatorsAndDocuments/RegulatorsSummaryHelperSpec.scala
Addition of the You Have Added One Authorised Official Page
> DDCE-794: Addition of the You Have Added One Authorised Official Page

- app/controllers/nominees/NomineeDetailsSummaryController.scala
- app/navigation/NomineesNavigator.scala
- app/pages/nominees/NomineeDetailsSummaryPage.scala
- app/viewmodels/nominees/NomineeDetailsSummaryHelper.scala
- conf/messages.cy
- conf/messages.en
- conf/officialsAndNominees.routes
- test/controllers/nominees/NomineeDetailsSummaryControllerSpec.scala
- test/navigation/NomineesNavigatorSpec.scala
- test/pages/nominees/NomineeDetailsSummaryPageSpec.scala
- test/viewModels/nominees/NomineeDetailsSummaryHelperSpec.scala
> DDCE-815: changes for Check your charity’s nominee details

- app/controllers/authorisedOfficials/AuthorisedOfficialsSummaryController.scala
- app/navigation/AuthorisedOfficialsNavigator.scala
- app/pages/addressLookup/AuthorisedOfficialAddressLookupPage.scala
- app/pages/authorisedOfficials/AuthorisedOfficialsSummaryPage.scala
- app/viewmodels/authorisedOfficials/AddedOneAuthorisedOfficialHelper.scala
- app/viewmodels/authorisedOfficials/AuthorisedOfficialsSummaryHelper.scala
- app/views/CheckYourAnswersView.scala.html
- conf/messages.cy
- conf/messages.en
- conf/officialsAndNominees.routes
- test/controllers/authorisedOfficials/AuthorisedOfficialsSummaryControllerSpec.scala
- test/navigation/AuthorisedOfficialsNavigatorSpec.scala
- test/pages/authorisedOfficials/AuthorisedOfficialsSummaryPageSpec.scala
- test/viewModels/authorisedOfficials/AddedOneAuthorisedOfficialHelperSpec.scala
- test/viewModels/authorisedOfficials/AuthorisedOfficialsSummaryHelperSpec.scala
Check your charity’s authorised officials details
> DDCE-796:Check your charity’s authorised officials details

- app/navigation/AuthorisedOfficialsNavigator.scala
- test/navigation/AuthorisedOfficialsNavigatorSpec.scala
##Bug fix
Amendment of Journey A
> DDCE-831: Amendment of Journey A for Authorised Officials Section

- app/navigation/DocumentsNavigator.scala
- app/viewmodels/regulatorsAndDocuments/GoverningDocumentSummaryHelper.scala
- test/navigation/DocumentsNavigatorSpec.scala
- test/viewModels/regulatorsAndDocuments/GoverningDocumentSummaryHelperSpec.scala
> DDCE-861: changes for P4 Journey 1 - Changes to governing document details

- app/views/checkEligibility/IsEligibleAccountView.scala.html
- app/views/checkEligibility/IsEligibleLocationOtherView.scala.html
- app/views/checkEligibility/IsEligibleLocationView.scala.html
- app/views/checkEligibility/IsEligiblePurposeView.scala.html
- conf/messages.cy
- conf/messages.en
- test/views/checkEligibility/IsEligibleAccountViewSpec.scala
- test/views/checkEligibility/IsEligibleLocationOtherViewSpec.scala
- test/views/checkEligibility/IsEligibleLocationViewSpec.scala
- test/views/checkEligibility/IsEligiblePurposeViewSpec.scala
##Bug fix 
Removed 'Check if you can register' tagline from all pages
> DDCE-866:Remove 'Check if you can register' tagline from all pages

- app/navigation/DocumentsNavigator.scala
- app/viewmodels/regulatorsAndDocuments/GoverningDocumentSummaryHelper.scala
- test/navigation/DocumentsNavigatorSpec.scala
- test/navigation/NomineesNavigatorSpec.scala
- test/viewModels/regulatorsAndDocuments/GoverningDocumentSummaryHelperSpec.scala
- test/views/common/DateOfBirthViewSpec.scala
- test/views/common/NameViewSpec.scala
- test/views/common/NinoViewSpec.scala
- test/views/common/OfficialsPositionViewSpec.scala
- test/views/common/PhoneNumberViewSpec.scala
> [DDCE-655]:§3 P4 Journey 1 - Changes to governing document details

- app/controllers/IndexController.scala
- app/controllers/otherOfficials/CharityOtherOfficialsController.scala
- app/views/TaskList.scala.html
- app/views/components/h1.scala.html
- app/views/otherOfficials/CharityOtherOfficialsView.scala.html
- conf/messages.cy
- conf/messages.en
- conf/officialsAndNominees.routes
- test/controllers/otherOfficials/CharityOtherOfficialsControllerSpec.scala
- test/views/otherOfficials/CharityOtherOfficialsViewSpec.scala
> DDCE-816: changes for P1 - Charity’s other officials

- app/navigation/DocumentsNavigator.scala
- app/viewmodels/regulatorsAndDocuments/GoverningDocumentSummaryHelper.scala
- test/navigation/DocumentsNavigatorSpec.scala
- test/viewModels/regulatorsAndDocuments/GoverningDocumentSummaryHelperSpec.scala
> DDCE-657:Changes to governing document details

- app/controllers/checkEligibility/CheckIfCanRegisterController.scala
- app/pages/checkEligibility/CheckIfCanRegisterPage.scala
- app/views/checkEligibility/CheckIfCanRegisterView.scala.html
- conf/checkEligibility.routes
- conf/messages.cy
- conf/messages.en
- test/controllers/checkEligibility/CheckIfCanRegisterControllerSpec.scala
- test/pages/checkEligibility/CheckIfCanRegisterPageSpec.scala
- test/views/checkEligibility/CheckIfCanRegisterViewSpec.scala
Addition of Check you can register the charity page in eligibility journey
> DDCE-871: Added check if you can register page as part of eligibility journey

- app/controllers/checkEligibility/InEligibleCharitablePurposesController.scala
- app/navigation/EligibilityNavigator.scala
- app/views/checkEligibility/InEligibleCharitablePurposesView.scala.html
- conf/checkEligibility.routes
- conf/messages.cy
- conf/messages.en
- test/controllers/checkEligibility/InEligibleCharitablePurposesControllerSpec.scala
- test/navigation/EligibilityNavigatorSpec.scala
- test/views/checkEligibility/InEligibleCharitablePurposesViewSpec.scala
##New feature 
Not Eligible 1 Page
> Ddce 872:Not Eligible 1 Page

- app/controllers/LocalBaseController.scala
- app/controllers/addressLookup/AuthorisedOfficialsAddressLookupController.scala
- app/controllers/authorisedOfficials/AuthorisedOfficialPreviousAddressController.scala
- app/controllers/authorisedOfficials/AuthorisedOfficialsDOBController.scala
- app/controllers/authorisedOfficials/AuthorisedOfficialsNinoController.scala
- app/controllers/authorisedOfficials/AuthorisedOfficialsPhoneNumberController.scala
- app/controllers/authorisedOfficials/AuthorisedOfficialsPositionController.scala
- app/controllers/authorisedOfficials/IsAuthorisedOfficialNinoController.scala
- app/controllers/otherOfficials/OtherOfficialsNameController.scala
- app/navigation/OtherOfficialsNavigator.scala
- app/pages/otherOfficials/OtherOfficialsId.scala
- app/pages/otherOfficials/OtherOfficialsNamePage.scala
- app/viewmodels/authorisedOfficials/AddedOneAuthorisedOfficialHelper.scala
- app/views/common/NameView.scala.html
- app/views/otherOfficials/CharityOtherOfficialsView.scala.html
- conf/messages.cy
- conf/messages.en
- conf/officialsAndNominees.routes
- test/controllers/LocalBaseControllerSpec.scala
- test/controllers/otherOfficials/OtherOfficialsNameControllerSpec.scala
- test/models/CommonModelSpec.scala
- test/navigation/FakeNavigators.scala
- test/navigation/OtherOfficialsNavigatorSpec.scala
- test/pages/otherOfficials/OtherOfficialsIdSpec.scala
- test/pages/otherOfficials/OtherOfficialsNamePageSpec.scala
- test/views/common/NameViewSpec.scala
- test/views/otherOfficials/CharityOtherOfficialsViewSpec.scala
> [DDCE-818]:§8 P2 - What is the other official’s name?

- conf/messages.cy
- conf/messages.en
> DDCE-867:Updated error message on the Eligibility question 2 page

- app/controllers/otherOfficials/OtherOfficialsDOBController.scala
- app/navigation/OtherOfficialsNavigator.scala
- app/pages/otherOfficials/OtherOfficialsDOBPage.scala
- app/views/TaskList.scala.html
- conf/messages.cy
- conf/messages.en
- conf/officialsAndNominees.routes
- test/controllers/otherOfficials/OtherOfficialsDOBControllerSpec.scala
- test/navigation/AuthorisedOfficialsNavigatorSpec.scala
- test/navigation/OtherOfficialsNavigatorSpec.scala
- test/pages/otherOfficials/OtherOfficialsDOBPageSpec.scala
> DDCE-819: changes for P3 - What is [Full name]'s date of birth?

- app/controllers/checkEligibility/InEligibleBankController.scala
- app/navigation/EligibilityNavigator.scala
- app/views/checkEligibility/InEligibleBankView.scala.html
- conf/checkEligibility.routes
- conf/messages.cy
- conf/messages.en
- test/controllers/checkEligibility/InEligibleBankControllerSpec.scala
- test/navigation/EligibilityNavigatorSpec.scala
- test/views/checkEligibility/InEligibleBankViewSpec.scala
> DDCE-873:Not eligible second page

- app/controllers/otherOfficials/OtherOfficialsPhoneNumberController.scala
- app/navigation/OtherOfficialsNavigator.scala
- app/pages/otherOfficials/OtherOfficialsPhoneNumberPage.scala
- conf/messages.cy
- conf/messages.en
- conf/officialsAndNominees.routes
- test/controllers/otherOfficials/OtherOfficialsPhoneNumberControllerSpec.scala
- test/forms/common/NameFormProviderSpec.scala
- test/navigation/AuthorisedOfficialsNavigatorSpec.scala
- test/navigation/OtherOfficialsNavigatorSpec.scala
- test/pages/otherOfficials/OtherOfficialsPhoneNumberPageSpec.scala
> DDCE-820: changes for P4 - What is [Full name]'s phone number?

- app/controllers/common/NinoController.scala
- app/controllers/otherOfficials/OtherOfficialsNinoController.scala
- app/navigation/OtherOfficialsNavigator.scala
- app/pages/otherOfficials/OtherOfficialsNinoPage.scala
- conf/messages.cy
- conf/messages.en
- conf/officialsAndNominees.routes
- test/controllers/otherOfficials/OtherOfficialsNinoControllerSpec.scala
- test/navigation/OtherOfficialsNavigatorSpec.scala
- test/pages/otherOfficials/OtherOfficialsNinoPageSpec.scala
##New feature 
What is [Full name]’s National Insurance number?
> DDCE-823:What is [Full name]’s National Insurance number?

- app/controllers/otherOfficials/IsOtherOfficialNinoController.scala
- app/navigation/OtherOfficialsNavigator.scala
- app/pages/otherOfficials/IsOtherOfficialNinoPage.scala
- conf/messages.cy
- conf/messages.en
- conf/officialsAndNominees.routes
- test/controllers/LocalBaseControllerSpec.scala
- test/controllers/addressLookup/AuthroisedOfficialsAddressLookupControllerSpec.scala
- test/controllers/authorisedOfficials/AuthorisedOfficialPreviousAddressControllerSpec.scala
- test/controllers/authorisedOfficials/AuthorisedOfficialsDOBControllerSpec.scala
- test/controllers/authorisedOfficials/AuthorisedOfficialsNameControllerSpec.scala
- test/controllers/authorisedOfficials/AuthorisedOfficialsNinoControllerSpec.scala
- test/controllers/authorisedOfficials/AuthorisedOfficialsPositionControllerSpec.scala
- test/controllers/otherOfficials/IsOtherOfficialNinoControllerSpec.scala
- test/controllers/otherOfficials/OtherOfficialsDOBControllerSpec.scala
- test/controllers/otherOfficials/OtherOfficialsNameControllerSpec.scala
- test/controllers/otherOfficials/OtherOfficialsPositionControllerSpec.scala
- test/navigation/OtherOfficialsNavigatorSpec.scala
- test/pages/authorisedOfficials/AuthorisedOfficialsNamePageSpec.scala
- test/pages/otherOfficials/IsOtherOfficialNinoPageSpec.scala
> DDCE-822: changes for P6 - Does [Full name] have a National Insurance number?

- app/controllers/otherOfficials/OtherOfficialsPreviousAddressController.scala
- app/navigation/OtherOfficialsNavigator.scala
- app/pages/otherOfficials/OtherOfficialsPreviousAddressPage.scala
- conf/messages.cy
- conf/messages.en
- conf/officialsAndNominees.routes
- test/controllers/otherOfficials/OtherOfficialsPreviousAddressControllerSpec.scala
- test/navigation/OtherOfficialsNavigatorSpec.scala
- test/pages/otherOfficials/OtherOfficialsPreviousAddressPageSpec.scala
Has the other official's address changed in the last 12 months?
> Ddce 827 Has the other official's address changed in the last 12 months?

- app/controllers/otherOfficials/AddSecondOtherOfficialsController.scala
- app/navigation/OtherOfficialsNavigator.scala
- app/views/otherOfficials/AddSecondOtherOfficialsView.scala.html
- conf/messages.cy
- conf/messages.en
- conf/officialsAndNominees.routes
- test/controllers/otherOfficials/AddSecondOtherOfficialsControllerSpec.scala
- test/navigation/OtherOfficialsNavigatorSpec.scala
- test/views/otherOfficials/AddOtherOfficialsViewSpec.scala
> DDCE-829: changes for P12 - You will be adding the second official in the next page

- app/controllers/nominees/ChooseNomineeController.scala
- app/forms/nominees/ChooseNomineeFormProvider.scala
- app/navigation/NomineesNavigator.scala
- app/pages/nominees/ChooseNomineePage.scala
- app/views/nominees/ChooseNomineeView.scala.html
- conf/messages.cy
- conf/messages.en
- conf/officialsAndNominees.routes
- test/controllers/nominees/ChooseNomineeControllerSpec.scala
- test/forms/nominees/ChooseNomineeFormProviderSpec.scala
- test/navigation/NomineesNavigatorSpec.scala
- test/pages/nominees/ChooseNomineePageSpec.scala
- test/views/nominees/ChooseNomineeViewSpec.scala
Is the nominee an individual or an organisation?
> DDCE-895:Is the nominee an individual or an organisation?

- app/controllers/authorisedOfficials/AddedOneAuthorisedOfficialController.scala
- app/controllers/otherOfficials/AddedOneOtherOfficialController.scala
- app/navigation/OtherOfficialsNavigator.scala
- app/pages/otherOfficials/AddedOneOtherOfficialPage.scala
- app/views/otherOfficials/AddSecondOtherOfficialsView.scala.html
- test/controllers/otherOfficials/AddSecondOtherOfficialsControllerSpec.scala
- test/navigation/OtherOfficialsNavigatorSpec.scala
- test/views/otherOfficials/AddSecondOtherOfficialsViewSpec.scala
> [DDCE-830]:§8 Second Loop of Offical's Details

- app/controllers/DeclarationController.scala
- app/views/DeclarationView.scala.html
- conf/app.routes
- conf/messages.cy
- conf/messages.en
- test/controllers/DeclarationControllerSpec.scala
- test/views/DeclarationViewSpec.scala
##New feature
Declaration Page
> DDCE-934:Declaration Page

- app/config/FrontendAppConfig.scala
- app/views/templates/GovukLayoutWrapper.scala.html
- conf/application.conf
- test/config/FrontendAppConfigSpec.scala
> DDCE-931: changes for signout link

- app/controllers/IndexController.scala
- app/controllers/authorisedOfficials/AddedOneAuthorisedOfficialController.scala
- app/controllers/common/AddedOfficialController.scala
- app/controllers/otherOfficials/AddedSecondOtherOfficialController.scala
- app/navigation/OtherOfficialsNavigator.scala
- app/pages/otherOfficials/AddedSecondOtherOfficialPage.scala
- app/views/CheckYourAnswersView.scala.html
- conf/messages.cy
- conf/messages.en
- conf/officialsAndNominees.routes
- test/controllers/otherOfficials/AddedSecondOtherOfficialControllerSpec.scala
- test/navigation/OtherOfficialsNavigatorSpec.scala
- test/pages/otherOfficials/AddedSecondOtherOfficialPageSpec.scala
> DDCE-868:changes for P11.2 - Check the second other official’s details

- app/views/TaskList.scala.html
- test/navigation/OtherOfficialsNavigatorSpec.scala
- test/views/TaskListViewSpec.scala
> [DDCE-629]:Change Task List Status Tags to HMRC Design Pattern

- app/controllers/otherOfficials/AddAnotherOtherOfficialController.scala
- app/navigation/OtherOfficialsNavigator.scala
- app/pages/otherOfficials/AddAnotherOtherOfficialPage.scala
- app/views/otherOfficials/AddAnotherOtherOfficialView.scala.html
- conf/messages.cy
- conf/messages.en
- conf/officialsAndNominees.routes
- test/controllers/otherOfficials/AddAnotherOtherOfficialControllerSpec.scala
- test/navigation/OtherOfficialsNavigatorSpec.scala
- test/pages/otherOfficials/AddAnotherOtherOfficialPageSpec.scala
- test/views/otherOfficials/AddAnotherOtherOfficialViewSpec.scala
##New feature
Do you want to add another other official?
> DDCE-869:Do you want to add another other official?

- app/controllers/otherOfficials/IsOtherOfficialNinoController.scala
- app/controllers/otherOfficials/OtherOfficialsPhoneNumberController.scala
- app/controllers/otherOfficials/OtherOfficialsSummaryController.scala
- app/navigation/OtherOfficialsNavigator.scala
- app/pages/otherOfficials/OtherOfficialsSummaryPage.scala
- app/viewmodels/authorisedOfficials/AddedOfficialsSummaryHelper.scala
- app/views/otherOfficials/OtherOfficialsSummaryView.scala.html
- conf/messages.cy
- conf/messages.en
- conf/officialsAndNominees.routes
- test/controllers/otherOfficials/OtherOfficialsSummaryControllerSpec.scala
- test/navigation/OtherOfficialsNavigatorSpec.scala
- test/pages/otherOfficials/OtherOfficialsSummaryPageSpec.scala
- test/viewModels/authorisedOfficials/AddedOfficialsSummaryHelperSpec.scala
##New feature (delete as appropriate)
Addition of other officials summary page.
> DDCE-870: other officials summary page (requires navigation and rebase based on DDCE-869 changes)

- app/controllers/RegistrationSentController.scala
- app/views/DeclarationView.scala.html
- app/views/RegistrationSentView.scala.html
- conf/app.routes
- conf/messages.cy
- conf/messages.en
- test/controllers/RegistrationSentControllerSpec.scala
- test/views/RegistrationSentViewSpec.scala
> DDCE-935:Registration Sent Confirmation page creation

- app/navigation/FundRaisingNavigator.scala
- app/viewmodels/operationsAndFunds/OperationsFundsSummaryHelper.scala
- test/navigation/FundRaisingNavigatorSpec.scala
- test/viewModels/operationsAndFunds/OperationsFundsSummaryHelperSpec.scala
> Ddce 955:P8 Journeys 1, 3 & 9

- conf/messages.cy
- conf/messages.en
> [DDCE-982]:Amend row labels on summary page

- app/controllers/charityInformation/CharityInformationController.scala
- app/utils/TaskListHelper.scala
- app/views/charityInformation/CharityInformationView.scala.html
- conf/charityInformation.routes
- conf/messages.cy
- conf/messages.en
- test/controllers/charityInformation/CharityInformationControllerSpec.scala
- test/utils/TaskListHelperSpec.scala
- test/views/charityInformation/CharityInformationViewSpec.scala
> DDCE-958:Section 1 Warm-up Page: The charity's information

- app/views/charityInformation/CharityInformationView.scala.html
##Bug fix 
Section 1 Warm-up Page: The charity's information
> DDCE 958:Section 1 Warm-up Page: The charity's information

- app/controllers/regulatorsAndDocuments/StartCharityRegulatorController.scala
- app/utils/TaskListHelper.scala
- app/views/regulatorsAndDocuments/CharityOtherRegulatorDetailsView.scala.html
- app/views/regulatorsAndDocuments/StartCharityRegulatorView.scala.html
- conf/messages.cy
- conf/messages.en
- conf/regulatorsAndDocuments.routes
- test/controllers/regulatorsAndDocuments/StartCharityRegulatorControllerSpec.scala
- test/utils/TaskListHelperSpec.scala
- test/views/regulatorsAndDocuments/StartCharityRegulatorViewSpec.scala
##New feature
Warmup page for regulator's page section.
> DDCE-959: Added Charity Regulator's warmup page

- app/controllers/charityInformation/StartInformationController.scala
- app/controllers/regulatorsAndDocuments/StartGoverningDocumentController.scala
- app/utils/TaskListHelper.scala
- app/views/charityInformation/StartInformationView.scala.html
- app/views/regulatorsAndDocuments/StartGoverningDocumentView.scala.html
- conf/charityInformation.routes
- conf/messages.cy
- conf/messages.en
- conf/regulatorsAndDocuments.routes
- test/controllers/charityInformation/StartInformationControllerSpec.scala
- test/controllers/regulatorsAndDocuments/StartGoverningDocumentControllerSpec.scala
- test/utils/TaskListHelperSpec.scala
- test/views/charityInformation/StartInformationViewSpec.scala
- test/views/regulatorsAndDocuments/StartGoverningDocumentViewSpec.scala
##New feature
Section 3 Warm-up Page: The charity's governing document
> DDCE 960:Section 3 Warm-up Page: The charity's governing document

- app/controllers/addressLookup/CharityPostalAddressLookupController.scala
- app/navigation/CharityInformationNavigator.scala
- app/pages/addressLookup/CharityPostalAddressLookupPage.scala
- app/viewmodels/charityInformation/CharityInformationSummaryHelper.scala
- app/views/checkEligibility/IsEligibleLocationOtherView.scala.html
- conf/address.routes
- conf/messages.cy
- conf/messages.en
- test/controllers/addressLookup/CharityPostalAddressLookupControllerSpec.scala
- test/navigation/CharityInformationNavigatorSpec.scala
- test/pages/addressLookup/CharityPostalAddressLookupPageSpec.scala
- test/pages/charityInformation/CanWeSendToThisAddressPageSpec.scala
- test/viewModels/charityInformation/CharityInformationSummaryHelperSpec.scala
> [DDCE-615]:§1 P5A.1-P5C Postal Address Lookup (B Journey)

- app/controllers/actions/IdentifierAction.scala
- app/models/submission/CharityCommonTransformer.scala
- app/models/submission/CharityPartnerTransformer.scala
- app/models/submission/CharityRegistrationTransformer.scala
- app/models/submission/CharitySubmissionTransformer.scala
- app/models/submission/CharityTransformer.scala
- app/models/submission/JsonTransformer.scala
- app/pages/charityInformation/CanWeSendToThisAddressPage.scala
- test/controllers/actions/AuthActionSpec.scala
- test/controllers/addressLookup/AuthorisedOfficialsAddressLookupControllerSpec.scala
- test/controllers/authorisedOfficials/AuthorisedOfficialsDOBControllerSpec.scala
- test/models/submission/CharityCommonTransformerSpec.scala
- test/models/submission/JsonTransformerSpec.scala
> DDCE-975: changes for json reads for Data Conversion for 'Common' Object

- app/controllers/operationsAndFunds/StartCharitableObjectivesController.scala
- app/utils/TaskListHelper.scala
- app/views/operationsAndFunds/StartCharitableObjectivesView.scala.html
- conf/messages.cy
- conf/messages.en
- conf/operationsAndFunds.routes
- test/controllers/operationsAndFunds/StartCharitableObjectivesControllerSpec.scala
- test/utils/TaskListHelperSpec.scala
- test/views/operationsAndFunds/StartCharitableObjectivesViewSpec.scala
##New feature (delete as appropriate)
Warmup page for section 4
> DDCE-961: Added section 4 (charitable objectives) warmup page

- app/controllers/operationsAndFunds/StartFundraisingController.scala
- app/utils/TaskListHelper.scala
- app/views/operationsAndFunds/StartFundraisingView.scala.html
- conf/messages.cy
- conf/messages.en
- conf/operationsAndFunds.routes
- test/controllers/operationsAndFunds/StartFundraisingControllerSpec.scala
- test/utils/TaskListHelperSpec.scala
- test/views/operationsAndFunds/StartFundraisingViewSpec.scala
> DDCE-962: changes related to Add Section 5 Warm-up Page: The charity's s fundraising and operations

- app/views/TaskList.scala.html
- conf/messages.cy
- conf/messages.en
##New feature
Update Task List content to match prototype
> DDCE-1000:Update Task List content to match prototype

- app/connectors/httpParsers/ErrorResponse.scala
- app/controllers/addressLookup/OtherOfficialsAddressLookupController.scala
- app/controllers/common/AddedOfficialController.scala
> DDCE-1010: changes related to Authorised Officials + Other Officials Bug

- app/controllers/checkEligibility/EligibleCharityController.scala
- app/navigation/EligibilityNavigator.scala
- app/views/TaskList.scala.html
- app/views/checkEligibility/EligibleCharityView.scala.html
- conf/checkEligibility.routes
- conf/messages.cy
- conf/messages.en
- test/controllers/checkEligibility/EligibleCharityControllerSpec.scala
- test/navigation/EligibilityNavigatorSpec.scala
- test/views/checkEligibility/EligibleCharityViewSpec.scala
##New feature
Addition of Charity is eligible page to Eligibility journey
> DDCE-999: Added Charity is Eligible page to Eligibility Journey

- conf/messages.cy
- conf/messages.en
> DDCE-1006: Content Updates for P6 - Check the charity’s contact details

- conf/messages.cy
- conf/messages.en
> [DDCE-1004]:Content Update for P3A.1-3A.3 Address Lookup for Charity's Official Address

- app/views/checkEligibility/IsEligiblePurposeView.scala.html
- conf/messages.cy
- conf/messages.en
- test/views/behaviours/YesNoViewBehaviours.scala
- test/views/checkEligibility/IsEligiblePurposeViewSpec.scala
##New feature
Content Updates for Eligibility Check
> DDCE-993:Content Updates for Eligibility Check

- conf/messages.cy
- conf/messages.en
##New feature 
Content Update for P1 - What is the charity's name?
> DDCE-1002:Content Update for P1 - What is the charity's name?

- app/controllers/operationsAndFunds/StartBankDetailsController.scala
- app/utils/TaskListHelper.scala
- app/views/operationsAndFunds/StartBankDetailsView.scala.html
- conf/messages.cy
- conf/messages.en
- conf/operationsAndFunds.routes
- test/controllers/operationsAndFunds/StartBankDetailsControllerSpec.scala
- test/utils/TaskListHelperSpec.scala
- test/views/operationsAndFunds/StartBankDetailsViewSpec.scala
> DDCE-1018:Start Bank details page creation

- app/models/submission/CharityCommonTransformer.scala
- app/models/submission/CharityPartnerTransformer.scala
- app/models/submission/JsonTransformer.scala
- project/AppDependencies.scala
- test/models/submission/CharityCommonTransformerSpec.scala
- test/models/submission/CharityPartnerTransformerSpec.scala
- test/models/submission/JsonTransformerSpec.scala
> [DDCE-978]:Data Conversion for Partner object

- app/controllers/charityInformation/CanWeSendToThisAddressController.scala
- app/views/charityInformation/CanWeSendToThisAddressView.scala.html
- conf/messages.cy
- conf/messages.en
- test/controllers/charityInformation/CanWeSendToThisAddressControllerSpec.scala
- test/views/charityInformation/CanWeSendToThisAddressViewSpec.scala
> DDCE-1005: changes related to Design Update of can we send letters to this address

- app/controllers/charityInformation/CanWeSendToThisAddressController.scala
- app/navigation/CharityInformationNavigator.scala
- test/navigation/CharityInformationNavigatorSpec.scala
> DDCE-618: changes related to navigation from 'Send letters to this address' and 'Postal Address'

- app/views/regulatorsAndDocuments/CharityCommissionRegistrationNumberView.scala.html
- app/views/regulatorsAndDocuments/IsCharityRegulatorView.scala.html
- app/views/regulatorsAndDocuments/NIRegulatorRegNumberView.scala.html
- app/views/regulatorsAndDocuments/ScottishRegulatorRegNumberView.scala.html
- app/views/regulatorsAndDocuments/WhyNotRegisteredWithCharityView.scala.html
- conf/messages.cy
- conf/messages.en
> DDCE-1009:Amendments for section 2

- app/controllers/regulatorsAndDocuments/WhenGoverningDocumentApprovedController.scala
- app/views/regulatorsAndDocuments/WhenGoverningDocumentApprovedView.scala.html
- conf/messages.cy
- conf/messages.en
- test/controllers/regulatorsAndDocuments/WhenGoverningDocumentApprovedControllerSpec.scala
- test/views/regulatorsAndDocuments/WhenGoverningDocumentApprovedViewSpec.scala
> [DDCE-1012]:Content Updates for Section 3 - Governing Document

- app/views/operationsAndFunds/CharitableObjectivesView.scala.html
- app/views/operationsAndFunds/PublicBenefitsView.scala.html
- conf/messages.cy
- conf/messages.en
> DDCE-1008:Amendments for section four

- app/forms/operationsAndFunds/CharitableObjectivesFormProvider.scala
- app/views/operationsAndFunds/CharitableObjectivesView.scala.html
- conf/messages.cy
- conf/messages.en
- project/AppDependencies.scala
- project/plugins.sbt
- test/forms/operationsAndFunds/CharitableObjectivesFormProviderSpec.scala
> DDCE-1030: changes related to charitible objective character counter, data validation and error messages

- conf/messages.cy
- conf/messages.en
> DDCE-1021:Content updates for section nine

- app/views/otherOfficials/AddAnotherOtherOfficialView.scala.html
- conf/messages.cy
- conf/messages.en
- test/views/otherOfficials/AddAnotherOtherOfficialViewSpec.scala
> DDCE-1020: Content Updates for Section 8 - Other Officials

- app/views/common/NinoView.scala.html
> DDCE-1020: missing changes for Nino page

- app/navigation/CharityInformationNavigator.scala
- conf/messages.cy
- conf/messages.en
- test/assets/messages/SiteHeaderMessages.scala
- test/connectors/httpParsers/AddressLookupInitializationHttpParserSpec.scala
- test/connectors/httpParsers/CharitiesRegistrationHttpParserSpec.scala
- test/connectors/httpParsers/ConfirmedAddressHttpParserSpec.scala
- test/views/TaskListViewSpec.scala
> DDCE-1060: Change straight apostrophes to curly apostrophes

- conf/messages.cy
- conf/messages.en
##New feature
Content Updates for Section 5 - Operations and Funds
> DDCE-1014:Content Updates for Section 5 - Operations and Funds

- app/controllers/regulatorsAndDocuments/GoverningDocumentNameController.scala
- app/forms/regulatorsAndDocuments/GoverningDocumentNameFormProvider.scala
- app/models/submission/CharityTransformer.scala
- app/navigation/DocumentsNavigator.scala
- app/pages/regulatorsAndDocuments/GoverningDocumentNamePage.scala
- app/viewmodels/regulatorsAndDocuments/GoverningDocumentSummaryHelper.scala
- app/views/regulatorsAndDocuments/GoverningDocumentNameView.scala.html
- conf/messages.cy
- conf/messages.en
- conf/regulatorsAndDocuments.routes
- test/controllers/regulatorsAndDocuments/GoverningDocumentNameControllerSpec.scala
- test/forms/regulatorsAndDocuments/GoverningDocumentNameFormProviderSpec.scala
- test/models/submission/CharityTransformerSpec.scala
- test/navigation/DocumentsNavigatorSpec.scala
- test/pages/regulatorsAndDocuments/GoverningDocumentNamePageSpec.scala
- test/pages/regulatorsAndDocuments/SelectGoverningDocumentPageSpec.scala
- test/viewModels/regulatorsAndDocuments/GoverningDocumentSummaryHelperSpec.scala
- test/views/regulatorsAndDocuments/GoverningDocumentNameViewSpec.scala
What is the name of the governing document that was used to set up and run the charity?(B)
> DDCE-635:What is the name of the governing document that was used to set up and run the charity?

- app/audit/AuditEvent.scala
- app/audit/AuditService.scala
- app/audit/DeclarationAuditEvent.scala
- app/controllers/DeclarationController.scala
- app/views/DeclarationView.scala.html
- conf/app.routes
- test/audit/AuditServiceSpec.scala
- test/controllers/DeclarationControllerSpec.scala
- test/views/DeclarationViewSpec.scala
> DDCE-1029: Implementation of Declaration Audit event

- app/controllers/regulatorsAndDocuments/HasCharityChangedPartsOfGoverningDocumentController.scala
- app/forms/regulatorsAndDocuments/HasCharityChangedPartsOfGoverningDocumentFormProvider.scala
- app/models/submission/CharityTransformer.scala
- app/navigation/DocumentsNavigator.scala
- app/pages/regulatorsAndDocuments/HasCharityChangedPartsOfGoverningDocumentPage.scala
- app/viewmodels/regulatorsAndDocuments/GoverningDocumentSummaryHelper.scala
- app/views/regulatorsAndDocuments/HasCharityChangedPartsOfGoverningDocumentView.scala.html
- conf/messages.cy
- conf/messages.en
- conf/regulatorsAndDocuments.routes
- test/controllers/regulatorsAndDocuments/HasCharityChangedPartsOfGoverningDocumentControllerSpec.scala
- test/forms/regulatorsAndDocuments/HasCharityChangedPartsOfGoverningDocumentFormProviderSpec.scala
- test/models/submission/CharitySubmissionTransformerSpec.scala
- test/models/submission/CharityTransformerSpec.scala
- test/navigation/DocumentsNavigatorSpec.scala
- test/pages/regulatorsAndDocuments/HasCharityChangedPartsOfGoverningDocumentPageSpec.scala
- test/pages/regulatorsAndDocuments/IsApprovedGoverningDocumentPageSpec.scala
- test/viewModels/regulatorsAndDocuments/GoverningDocumentSummaryHelperSpec.scala
- test/views/regulatorsAndDocuments/HasCharityChangedPartsOfGoverningDocumentViewSpec.scala
##New feature 
Has the charity changed parts of the governing document since it was approved?
> DDCE: 651-Has the charity changed parts of the governing document since it was approved?

- app/connectors/httpParsers/AddressLookupInitializationHttpParser.scala
- app/connectors/httpParsers/CharitiesRegistrationHttpParser.scala
- app/connectors/httpParsers/ConfirmedAddressHttpParser.scala
- app/controllers/DeclarationController.scala
- app/models/submission/CharityCommonTransformer.scala
- app/models/submission/CharityPartnerTransformer.scala
- app/models/submission/CharitySubmissionTransformer.scala
- app/models/submission/CharityTransformer.scala
- app/navigation/DocumentsNavigator.scala
- app/pages/AcknowledgementReferencePage.scala
- app/service/CharitiesRegistrationService.scala
- test/controllers/DeclarationControllerSpec.scala
- test/models/submission/CharityCommonTransformerSpec.scala
- test/models/submission/CharityPartnerTransformerSpec.scala
- test/models/submission/CharitySubmissionTransformerSpec.scala
- test/models/submission/CharityTransformerSpec.scala
- test/models/submission/CharityTransformerTodoPages.scala
- test/service/CharitiesRegistrationServiceSpec.scala
> DDCE-954: changes related to Data Integration for A-Journeys

- app/controllers/DeclarationController.scala
- app/controllers/RegistrationSentController.scala
- app/controllers/regulatorsAndDocuments/WhenGoverningDocumentApprovedController.scala
- test/controllers/RegistrationSentControllerSpec.scala
- test/controllers/regulatorsAndDocuments/WhenGoverningDocumentApprovedControllerSpec.scala
- test/pages/AcknowledgementReferencePageSpec.scala
> DDCE-969: changes to implement data clear-down on successful submission

- app/navigation/AuthorisedOfficialsNavigator.scala
- app/views/authorisedOfficials/CharityAuthorisedOfficialsView.scala.html
- test/navigation/AuthorisedOfficialsNavigatorSpec.scala
Added 2nd loop to the journey of adding authorised officials. Summary page for authorised official #2 will be worked on in 1032.
> [RS][DDCE-1031] Added 2nd loop to section 7.

- app/controllers/regulatorsAndDocuments/GoverningDocumentNameController.scala
- app/controllers/regulatorsAndDocuments/SelectGoverningDocumentController.scala
- app/navigation/DocumentsNavigator.scala
- app/pages/regulatorsAndDocuments/IsApprovedGoverningDocumentPage.scala
- app/pages/regulatorsAndDocuments/SelectGoverningDocumentPage.scala
- test/navigation/DocumentsNavigatorSpec.scala
- test/pages/regulatorsAndDocuments/IsApprovedGoverningDocumentPageSpec.scala
- test/pages/regulatorsAndDocuments/SelectGoverningDocumentPageSpec.scala
> DDCE-656: Changes to governing document details

- app/pages/regulatorsAndDocuments/HasCharityChangedPartsOfGoverningDocumentPage.scala
- test/navigation/DocumentsNavigatorSpec.scala
- test/pages/regulatorsAndDocuments/HasCharityChangedPartsOfGoverningDocumentPageSpec.scala
> DDCE-862:Sections and clauses change

- app/controllers/authorisedOfficials/AddedSecondAuthorisedOfficialController.scala
- app/controllers/common/AddedOfficialController.scala
- app/navigation/AuthorisedOfficialsNavigator.scala
- app/pages/authorisedOfficials/AddedSecondAuthorisedOfficialPage.scala
- conf/messages.cy
- conf/messages.en
- conf/officialsAndNominees.routes
- test/controllers/authorisedOfficials/AddedSecondAuthorisedOfficialControllerSpec.scala
- test/navigation/AuthorisedOfficialsNavigatorSpec.scala
- test/pages/authorisedOfficials/AddedSecondAuthorisedOfficialPageSpec.scala
- test/views/authorisedOfficials/CharityAuthorisedOfficialsViewSpec.scala
> [RS][DDCE-1032] Added summary for 2nd authorised official (section 7).

- app/controllers/RegistrationSentController.scala
- app/controllers/authorisedOfficials/AuthorisedOfficialsSummaryController.scala
- app/controllers/otherOfficials/OtherOfficialsSummaryController.scala
- app/models/submission/CharityTransformer.scala
- app/navigation/AuthorisedOfficialsNavigator.scala
- app/viewmodels/authorisedOfficials/AddedOfficialsSummaryHelper.scala
- app/views/common/OfficialsSummaryView.scala.html
- test/controllers/RegistrationSentControllerSpec.scala
- test/navigation/AuthorisedOfficialsNavigatorSpec.scala
- test/views/RegistrationSentViewSpec.scala
- test/views/authorisedOfficials/CharityAuthorisedOfficialsViewSpec.scala
- test/views/otherOfficials/CharityOtherOfficialsViewSpec.scala
> DDCE-799: Check your charity’s authorised officials details (Two authorised officials)

- app/navigation/OtherOfficialsNavigator.scala
- test/navigation/OtherOfficialsNavigatorSpec.scala
Third Loop of Other Official's Details
> DDCE-1047:Third Loop of Other Official's Details

- app/controllers/common/AddedOfficialController.scala
- app/controllers/otherOfficials/AddedThirdOtherOfficialController.scala
- app/navigation/OtherOfficialsNavigator.scala
- app/pages/otherOfficials/AddedThirdOtherOfficialPage.scala
- app/viewmodels/CheckYourAnswersHelper.scala
- app/viewmodels/authorisedOfficials/AddedOneAuthorisedOfficialHelper.scala
- app/viewmodels/otherOfficials/AddedOneOtherOfficialHelper.scala
- conf/messages.cy
- conf/messages.en
- conf/officialsAndNominees.routes
- test/controllers/otherOfficials/AddedThirdOtherOfficialControllerSpec.scala
- test/controllers/regulatorsAndDocuments/HasCharityChangedPartsOfGoverningDocumentControllerSpec.scala
- test/navigation/OtherOfficialsNavigatorSpec.scala
- test/pages/otherOfficials/AddedThirdOtherOfficialPageSpec.scala
> DDCE-1044: Check the third other official’s details

- app/models/operations/CharitablePurposes.scala
- app/models/operations/FundRaisingOptions.scala
- app/models/operations/OperatingLocationOptions.scala
- app/models/regulators/CharityRegulator.scala
- test/views/behaviours/CheckboxViewBehaviours.scala
> DDCE-1063: Fix error message link on checkbox pages

- test/navigation/AuthorisedOfficialsNavigatorSpec.scala
> [RS][DDCE-1037] Added tests for 2nd auth official's change buttons.

- app/models/CommonModels.scala
- app/navigation/AuthorisedOfficialsNavigator.scala
- app/viewmodels/CheckYourAnswersHelper.scala
- test/controllers/regulatorsAndDocuments/SectionsChangedGoverningDocumentControllerSpec.scala
- test/models/CommonModelSpec.scala
- test/navigation/AuthorisedOfficialsNavigatorSpec.scala
- test/viewModels/authorisedOfficials/AddedOneAuthorisedOfficialHelperSpec.scala
- test/viewModels/otherOfficials/AddedOneOtherOfficialHelperSpec.scala
> DDCE-1103: Displaying Title in Playback and Summary Pages

- app/controllers/operationsAndFunds/OtherFundRaisingController.scala
- app/forms/operationsAndFunds/OtherFundRaisingFormProvider.scala
- app/navigation/FundRaisingNavigator.scala
- app/pages/operationsAndFunds/OtherFundRaisingPage.scala
- app/viewmodels/operationsAndFunds/OperationsFundsSummaryHelper.scala
- app/views/operationsAndFunds/OtherFundRaisingView.scala.html
- conf/messages.cy
- conf/messages.en
- conf/operationsAndFunds.routes
- test/controllers/operationsAndFunds/OtherFundRaisingControllerSpec.scala
- test/forms/operationsAndFunds/FundRaisingFormProviderSpec.scala
- test/forms/operationsAndFunds/OtherFundRaisingFormProviderSpec.scala
- test/navigation/FundRaisingNavigatorSpec.scala
- test/pages/operationsAndFunds/OtherFundRaisingPageSpec.scala
- test/views/operationsAndFunds/OtherFundRaisingViewSpec.scala
> DDCE-1024:What other way will the charity raise funds

- app/audit/SubmissionAuditEvent.scala
- app/service/CharitiesRegistrationService.scala
- test/audit/AuditServiceSpec.scala
- test/service/CharitiesRegistrationServiceSpec.scala
> [RS][DDCE-1033] Implemented submission audits.

- app/views/common/DateOfBirthView.scala.html
The legend for auth and other official's DOB pages didn't display their name properly, instead reading them out as {0}. This is a fix for that issue.
> [RS][DDCE-950] Fixed issue with legend not displaying name.

- app/controllers/LocalBaseController.scala
- app/controllers/authorisedOfficials/AuthorisedOfficialsPassportController.scala
- app/controllers/common/AddedOfficialController.scala
- app/controllers/common/PassportController.scala
- app/forms/common/PassportFormProvider.scala
- app/models/CommonModels.scala
- app/navigation/AuthorisedOfficialsNavigator.scala
- app/pages/authorisedOfficials/AuthorisedOfficialsPassportPage.scala
- app/viewmodels/CheckYourAnswersHelper.scala
- app/viewmodels/authorisedOfficials/AddedOneAuthorisedOfficialHelper.scala
- app/views/common/PassportView.scala.html
- conf/messages.cy
- conf/messages.en
- conf/officialsAndNominees.routes
- test/controllers/authorisedOfficials/AuthorisedOfficialsPassportControllerSpec.scala
- test/forms/common/PassportFormProviderSpec.scala
- test/navigation/AuthorisedOfficialsNavigatorSpec.scala
- test/pages/authorisedOfficials/AuthorisedOfficialsPassportPageSpec.scala
- test/viewModels/authorisedOfficials/AddedOneAuthorisedOfficialHelperSpec.scala
- test/views/common/PassportViewSpec.scala
> DDCE-1067:What is [Full name]’s passport or national identity card details

- app/controllers/operationsAndFunds/EstimatedIncomeController.scala
- app/forms/common/CurrencyFormProvider.scala
- app/forms/mappings/Formatters.scala
- app/forms/mappings/Mappings.scala
- app/navigation/FundRaisingNavigator.scala
- app/pages/operationsAndFunds/EstimatedIncomePage.scala
- app/viewmodels/CheckYourAnswersHelper.scala
- app/viewmodels/operationsAndFunds/OperationsFundsSummaryHelper.scala
- app/views/common/CurrencyView.scala.html
- app/views/components/inputCurrency.scala.html
- conf/messages.cy
- conf/messages.en
- conf/operationsAndFunds.routes
- test/controllers/operationsAndFunds/EstimatedIncomeControllerSpec.scala
- test/forms/behaviours/DecimalFieldBehaviours.scala
- test/forms/common/CurrencyFormProviderSpec.scala
- test/forms/mappings/MappingsSpec.scala
- test/navigation/FundRaisingNavigatorSpec.scala
- test/pages/operationsAndFunds/EstimatedIncomePageSpec.scala
- test/viewModels/operationsAndFunds/OperationsFundsSummaryHelperSpec.scala
- test/views/common/CurrencyViewSpec.scala
> [RS][DDCE-1026] Adding estimated income page to section 5.

- app/assets/stylesheets/application.scss
- app/controllers/operationsAndFunds/ActualIncomeController.scala
- app/models/submission/CharityTransformer.scala
- app/navigation/FundRaisingNavigator.scala
- app/pages/operationsAndFunds/ActualIncomePage.scala
- app/viewmodels/operationsAndFunds/OperationsFundsSummaryHelper.scala
- app/views/charityInformation/CharityContactDetailsView.scala.html
- app/views/charityInformation/CharityNameView.scala.html
- app/views/common/CurrencyView.scala.html
- app/views/common/DateOfBirthView.scala.html
- app/views/common/NameView.scala.html
- app/views/common/PassportView.scala.html
- app/views/common/PhoneNumberView.scala.html
- app/views/components/inputCurrency.scala.html
- app/views/operationsAndFunds/AccountingPeriodEndDateView.scala.html
- app/views/operationsAndFunds/BankDetailsView.scala.html
- app/views/operationsAndFunds/CharitableObjectivesView.scala.html
- app/views/regulatorsAndDocuments/CharityOtherRegulatorDetailsView.scala.html
- app/views/regulatorsAndDocuments/WhenGoverningDocumentApprovedView.scala.html
- conf/messages.cy
- conf/messages.en
- conf/operationsAndFunds.routes
- test/controllers/operationsAndFunds/ActualIncomeControllerSpec.scala
- test/models/submission/CharitySubmissionTransformerSpec.scala
- test/models/submission/CharityTransformerSpec.scala
- test/models/submission/CharityTransformerTodoPages.scala
- test/navigation/FundRaisingNavigatorSpec.scala
- test/pages/operationsAndFunds/ActualIncomeSpec.scala
- test/viewModels/operationsAndFunds/OperationsFundsSummaryHelperSpec.scala
- test/views/common/CurrencyViewSpec.scala
> [RS][DDCE-1027] Added actual income page.

- app/controllers/operationsAndFunds/WhatCountryDoesTheCharityOperateInController.scala
- app/forms/operationsAndFunds/WhatCountryDoesTheCharityOperateInFormProvider.scala
- app/navigation/FundRaisingNavigator.scala
- app/pages/operationsAndFunds/WhatCountryDoesTheCharityOperateInPage.scala
- app/views/common/PassportView.scala.html
- app/views/components/autocompleteCountryList.scala.html
- app/views/operationsAndFunds/WhatCountryDoesTheCharityOperateInView.scala.html
- conf/messages.cy
- conf/messages.en
- conf/operationsAndFunds.routes
- test/controllers/operationsAndFunds/WhatCountryDoesTheCharityOperateInControllerSpec.scala
- test/forms/operationsAndFunds/WhatCountryDoesTheCharityOperateInFormProviderSpec.scala
- test/navigation/FundRaisingNavigatorSpec.scala
- test/pages/operationsAndFunds/WhatCountryDoesTheCharityOperateInPageSpec.scala
- test/views/operationsAndFunds/WhatCountryDoesTheCharityOperateInViewSpec.scala
##New feature
What country does the charity operate in?
> DDCE-1069:What country does the charity operate in?

- app/navigation/FundRaisingNavigator.scala
- app/viewmodels/operationsAndFunds/OperationsFundsSummaryHelper.scala
- app/viewmodels/operationsAndFunds/OverseasOperatingLocationSummaryHelper.scala
- test/assets/messages/BaseMessages.scala
- test/controllers/operationsAndFunds/OverseasOperatingLocationSummaryControllerSpec.scala
- test/navigation/FundRaisingNavigatorSpec.scala
- test/viewModels/authorisedOfficials/AddedOneAuthorisedOfficialHelperSpec.scala
- test/viewModels/operationsAndFunds/OverseasOperatingLocationSummaryHelperSpec.scala
> DDCE-1091: Add overseas row to P8 - Check your charity’s operations and funds details

- app/controllers/nominees/IndividualNomineeNameController.scala
- app/models/submission/CharityPartnerTransformer.scala
- app/navigation/NomineesNavigator.scala
- app/pages/nominees/IndividualNomineeNamePage.scala
- app/views/common/NameView.scala.html
- conf/messages.cy
- conf/messages.en
- conf/officialsAndNominees.routes
- test/controllers/nominees/IndividualNomineeNameControllerSpec.scala
- test/navigation/NomineesNavigatorSpec.scala
- test/pages/nominees/IndividualNomineeNamePageSpec.scala
Stored under `__ \ "nomineeIndividual" \ "nomineeName"` to keep it similar to the officials' layout. 
> [RS][DDCE-898] Added individual nominee's name page.

- app/controllers/nominees/WhatIsTheNameOfTheOrganisationController.scala
- app/forms/nominees/WhatIsTheNameOfOrganisationFormProvider.scala
- app/navigation/NomineesNavigator.scala
- app/pages/nominees/WhatIsTheNameOfOrganisationPage.scala
- app/views/nominees/WhatIsTheNameOfTheOrganisationView.scala.html
- conf/messages.cy
- conf/messages.en
- conf/officialsAndNominees.routes
- test/controllers/nominees/WhatIsTheNameOfOrganisationControllerSpec.scala
- test/forms/nominees/WhatIsTheNameOfOrganisationFormProviderSpec.scala
- test/navigation/NomineesNavigatorSpec.scala
- test/pages/nominees/WhatIsTheNameOfOrganisationPageSpec.scala
- test/views/nominees/WhatIsTheNameOfTheOrganisationViewSpec.scala
##New feature
What is the name of organisation
> DDCE-910:What is the name of organisation

- app/controllers/addressLookup/AuthorisedOfficialsPreviousAddressLookupController.scala
- app/controllers/authorisedOfficials/IsAuthorisedOfficialPreviousAddressController.scala
- app/controllers/otherOfficials/OtherOfficialsPreviousAddressController.scala
- app/navigation/AuthorisedOfficialsNavigator.scala
- app/navigation/OtherOfficialsNavigator.scala
- app/pages/addressLookup/AuthorisedOfficialPreviousAddressLookupPage.scala
- app/pages/authorisedOfficials/IsAuthorisedOfficialPreviousAddressPage.scala
- app/pages/otherOfficials/IsOtherOfficialsPreviousAddressPage.scala
- app/viewmodels/authorisedOfficials/AddedOneAuthorisedOfficialHelper.scala
- app/viewmodels/otherOfficials/AddedOneOtherOfficialHelper.scala
- conf/address.routes
- conf/messages.cy
- conf/messages.en
- conf/officialsAndNominees.routes
- test/controllers/addressLookup/AuthorisedOfficialsPreviousAddressLookupControllerSpec.scala
- test/controllers/authorisedOfficials/IsAuthorisedOfficialPreviousAddressControllerSpec.scala
- test/controllers/otherOfficials/OtherOfficialsPreviousAddressControllerSpec.scala
- test/navigation/AuthorisedOfficialsNavigatorSpec.scala
- test/navigation/OtherOfficialsNavigatorSpec.scala
- test/pages/addressLookup/AuthorisedOfficialAddressLookupPageSpec.scala
- test/pages/addressLookup/AuthorisedOfficialPreviousAddressLookupPageSpec.scala
- test/pages/authorisedOfficials/IsAuthorisedOfficialPreviousAddressPageSpec.scala
- test/pages/otherOfficials/IsOtherOfficialsPreviousAddressPageSpec.scala
- test/viewModels/authorisedOfficials/AddedOneAuthorisedOfficialHelperSpec.scala
- test/viewModels/otherOfficials/AddedOneOtherOfficialHelperSpec.scala
- test/views/common/IsPreviousAddressViewSpec.scala
> DDCE-1064: Authorised official Previous Address Lookup

- app/controllers/nominees/IndividualNomineeDOBController.scala
- app/navigation/NomineesNavigator.scala
- app/pages/nominees/IndividualNomineeDOBPage.scala
- app/pages/nominees/NomineeId.scala
- app/pages/nominees/WhatIsTheNameOfOrganisationPage.scala
- conf/messages.cy
- conf/messages.en
- conf/officialsAndNominees.routes
- test/controllers/nominees/IndividualNomineeDOBControllerSpec.scala
- test/navigation/NomineesNavigatorSpec.scala
- test/pages/nominees/IndividualNomineeDOBPageSpec.scala
> DDCE-899:Nominee date of birth page creation

- app/controllers/nominees/IndividualNomineesPhoneNumberController.scala
- app/navigation/NomineesNavigator.scala
- app/pages/nominees/IndividualNomineesPhoneNumberPage.scala
- conf/messages.cy
- conf/messages.en
- conf/officialsAndNominees.routes
- test/controllers/nominees/IndividualNomineePhoneNumberControllerSpec.scala
- test/navigation/NomineesNavigatorSpec.scala
- test/pages/nominees/IndividualNomineePhoneNumberPageSpec.scala
##New feature
What is the nominee's phone number?
> DDCE-903:What is the nominee's phone number?

- app/controllers/nominees/IsIndividualNomineeNinoController.scala
- app/navigation/NomineesNavigator.scala
- app/pages/nominees/IsIndividualNomineeNinoPage.scala
- conf/messages.cy
- conf/messages.en
- conf/officialsAndNominees.routes
- test/controllers/nominees/IsIndividualNomineeNinoControllerSpec.scala
- test/navigation/NomineesNavigatorSpec.scala
- test/pages/nominees/IsIndividualNomineeNinoPageSpec.scala
> DDCE-904:Does Nominee have national insurance number page

- app/controllers/addressLookup/OtherOfficialsPreviousAddressLookupController.scala
- app/controllers/otherOfficials/IsOtherOfficialsPreviousAddressController.scala
- app/navigation/OtherOfficialsNavigator.scala
- app/pages/addressLookup/OtherOfficialPreviousAddressLookupPage.scala
- app/viewmodels/authorisedOfficials/AddedOneAuthorisedOfficialHelper.scala
- app/viewmodels/otherOfficials/AddedOneOtherOfficialHelper.scala
- build.sbt
- conf/address.routes
- conf/messages.cy
- conf/messages.en
- conf/officialsAndNominees.routes
- project/AppDependencies.scala
- project/plugins.sbt
- test/controllers/addressLookup/OtherOfficialsPreviousAddressLookupControllerSpec.scala
- test/controllers/otherOfficials/IsOtherOfficialsPreviousAddressControllerSpec.scala
- test/navigation/OtherOfficialsNavigatorSpec.scala
- test/pages/addressLookup/OtherOfficialPreviousAddressLookupPageSpec.scala
- test/viewModels/authorisedOfficials/AddedOneAuthorisedOfficialHelperSpec.scala
- test/viewModels/otherOfficials/AddedOneOtherOfficialHelperSpec.scala
> DDCE-1066: Authorised official Previous Address Lookup

- app/controllers/nominees/IndividualNomineesNinoController.scala
- app/navigation/NomineesNavigator.scala
- app/pages/nominees/IndividualNomineesNinoPage.scala
- conf/messages.cy
- conf/messages.en
- conf/officialsAndNominees.routes
- test/controllers/nominees/IndividualNomineeNinoControllerSpec.scala
- test/navigation/NomineesNavigatorSpec.scala
- test/pages/nominees/IndividualNomineerNinoPageSpec.scala
What is the nominee's national insurance number?
> DDCE-905:What is the nominee's national insurance number?

- app/navigation/AuthorisedOfficialsNavigator.scala
- app/pages/authorisedOfficials/IsAuthorisedOfficialNinoPage.scala
- test/navigation/AuthorisedOfficialsNavigatorSpec.scala
- test/pages/authorisedOfficials/IsAuthorisedOfficialNinoPageSpec.scala
> [RS][DDCE-1036] Added remaining change links for auth official playback.

- app/controllers/LocalBaseController.scala
- app/controllers/nominees/OrganisationNomineeContactDetailsController.scala
- app/controllers/nominees/OrganisationNomineeNameController.scala
- app/forms/nominees/OrganisationNomineeContactDetailsFormProvider.scala
- app/forms/nominees/OrganisationNomineeNameFormProvider.scala
- app/models/nominees/OrganisationNomineeContactDetails.scala
- app/navigation/NomineesNavigator.scala
- app/pages/nominees/OrganisationNomineeContactDetailsPage.scala
- app/pages/nominees/OrganisationNomineeNamePage.scala
- app/views/charityInformation/CharityContactDetailsView.scala.html
- app/views/components/autocompleteCountryList.scala.html
- app/views/components/inputText.scala.html
- app/views/nominees/OrganisationNomineeContactDetailsView.scala.html
- app/views/nominees/OrganisationNomineeNameView.scala.html
- conf/messages.cy
- conf/messages.en
- conf/officialsAndNominees.routes
- test/controllers/LocalBaseControllerSpec.scala
- test/controllers/nominees/OrganisationNomineeContactDetailsControllerSpec.scala
- test/controllers/nominees/OrganisationNomineeNameControllerSpec.scala
- test/forms/nominees/OrganisationNomineeContactDetailsFormProviderSpec.scala
- test/forms/nominees/OrganisationNomineeNameFormProviderSpec.scala
- test/models/nominees/OrganisationNomineeContactDetailsSpec.scala
- test/navigation/NomineesNavigatorSpec.scala
- test/pages/nominees/OrganisationNomineeContactDetailsPageSpec.scala
- test/pages/nominees/OrganisationNomineeNamePageSpec.scala
- test/views/nominees/WhatIsTheNameOfTheOrganisationViewSpec.scala
> [RS][DDCE-911] Added organisation contact details page.

- app/controllers/nominees/IsIndividualNomineePaymentsController.scala
- app/forms/nominees/IsIndividualNomineePaymentsFormProvider.scala
- app/navigation/NomineesNavigator.scala
- app/pages/nominees/IsIndividualNomineePaymentsPage.scala
- app/views/nominees/IsIndividualNomineePaymentsView.scala.html
- conf/messages.cy
- conf/messages.en
- conf/officialsAndNominees.routes
- test/controllers/nominees/IsIndividualNomineePaymentsControllerSpec.scala
- test/forms/nominees/IsIndividualNomineePaymentsFormProviderSpec.scala
- test/navigation/NomineesNavigatorSpec.scala
- test/pages/nominees/IsIndividualNomineePaymentsPageSpec.scala
- test/views/nominees/IsIndividualNomineePaymentsViewSpec.scala
> DDCE-908:Is Nominee authorised to receive payments page

- app/controllers/addressLookup/NomineeIndividualAddressLookupController.scala
- app/navigation/NomineesNavigator.scala
- app/pages/addressLookup/NomineeIndividualAddressLookupPage.scala
- conf/address.routes
- conf/messages.cy
- conf/messages.en
- test/controllers/addressLookup/NomineeIndividualAddressLookupControllerSpec.scala
- test/navigation/NomineesNavigatorSpec.scala
- test/pages/addressLookup/NomineeIndividualAddressLookupPageSpec.scala
> DDCE-906:P9A.1-P9A.3 Address Lookup

- app/controllers/addressLookup/OrganisationNomineeAddressLookupController.scala
- app/navigation/NomineesNavigator.scala
- app/pages/addressLookup/OrganisationNomineeAddressLookupPage.scala
- conf/address.routes
- conf/messages.cy
- conf/messages.en
- test/controllers/addressLookup/OrganisationNomineeAddressLookupControllerSpec.scala
- test/navigation/NomineesNavigatorSpec.scala
> [RS][DDCE-912] Added address lookup for organisation nominee.

- app/controllers/nominees/IsIndividualNomineePreviousAddressController.scala
- app/navigation/NomineesNavigator.scala
- app/pages/nominees/IsIndividualNomineePreviousAddressPage.scala
- conf/messages.cy
- conf/messages.en
- conf/officialsAndNominees.routes
- test/controllers/nominees/IsIndividualNomineePreviousAddressControllerSpec.scala
- test/navigation/NomineesNavigatorSpec.scala
- test/pages/nominees/IsIndividualNomineePreviousAddressPageSpec.scala
> DDCE-907:Nominee Home address change page

- app/controllers/nominees/IsOrganisationNomineePreviousAddressController.scala
- app/navigation/NomineesNavigator.scala
- app/pages/nominees/IsOrganisationNomineePreviousAddressPage.scala
- conf/messages.cy
- conf/messages.en
- conf/officialsAndNominees.routes
- test/controllers/nominees/IsOrganisationNomineePreviousAddressControllerSpec.scala
- test/navigation/NomineesNavigatorSpec.scala
- test/pages/nominees/IsOrganisationNomineePreviousAddressPageSpec.scala
> DDCE-913:Has [org names]'s address changed in the last 12 months

- app/controllers/common/IsNomineePaymentsController.scala
- app/controllers/nominees/IsOrganisationNomineePaymentsController.scala
- app/forms/common/IsNomineePaymentsFormProvider.scala
- app/navigation/NomineesNavigator.scala
- app/pages/nominees/IsOrganisationNomineePaymentsPage.scala
- app/views/common/IsNomineePaymentsView.scala.html
- conf/messages.cy
- conf/messages.en
- conf/officialsAndNominees.routes
- test/controllers/nominees/IsOrganisationNomineePaymentsControllerSpec.scala
- test/forms/common/IsNomineePaymentsFormProviderSpec.scala
- test/navigation/NomineesNavigatorSpec.scala
- test/pages/nominees/IsOrganisationNomineePaymentsPageSpec.scala
- test/views/common/IsNomineePaymentsViewSpec.scala
##New feature 
Is the nominee organisation authorised to receive payments for your charity?
> DDCE- 914:Is the nominee organisation authorised to receive payments for your charity?

- conf/messages.cy
- conf/messages.en
> DDCE-915: review comments for Oraganisation Name

- app/controllers/nominees/OrganisationNomineeAuthorisedPersonController.scala
- app/navigation/NomineesNavigator.scala
- app/views/nominees/OrganisationNomineeAuthorisedPersonView.scala.html
- conf/messages.cy
- conf/messages.en
- conf/officialsAndNominees.routes
- test/controllers/nominees/OrganisationNomineeAuthorisedPersonControllerSpec.scala
- test/navigation/NomineesNavigatorSpec.scala
- test/views/nominees/OrganisationNomineeAuthorisedPersonViewSpec.scala
> DDCE-916:Add an authorised person from nominee organisation

- app/controllers/nominees/OrganisationAuthorisedPersonNameController.scala
- app/navigation/NomineesNavigator.scala
- app/pages/nominees/OrganisationAuthorisedPersonNamePage.scala
- app/views/common/NameView.scala.html
- app/views/nominees/OrganisationNomineeAuthorisedPersonView.scala.html
- conf/messages.cy
- conf/messages.en
- conf/officialsAndNominees.routes
- test/controllers/nominees/OrganisationAuthorisedPersonNameControllerSpec.scala
- test/navigation/NomineesNavigatorSpec.scala
- test/pages/nominees/OrganisationAuthorisedPersonNamePageSpec.scala
- test/views/nominees/OrganisationNomineeAuthorisedPersonViewSpec.scala
> DDCE-917:Authorised person’s name

- app/config/FrontendAppConfig.scala
- app/controllers/DeclarationController.scala
- app/models/CharityInformation.scala
- app/navigation/AuthorisedOfficialsNavigator.scala
- app/navigation/CharityInformationNavigator.scala
- app/navigation/NomineesNavigator.scala
- app/navigation/OtherOfficialsNavigator.scala
- conf/application.conf
- test/config/FrontendAppConfigSpec.scala
- test/controllers/DeclarationControllerSpec.scala
- test/navigation/CharityInformationNavigatorSpec.scala
- test/navigation/ExternalTestNavigationSpec.scala
> DDCE-1174: changes for External Tests Preparation

- app/controllers/nominees/IsOrganisationNomineeNinoController.scala
- app/navigation/NomineesNavigator.scala
- app/pages/nominees/IsOrganisationNomineeNinoPage.scala
- conf/messages.cy
- conf/messages.en
- conf/officialsAndNominees.routes
- test/controllers/nominees/IsOrganisationNomineeNinoControllerSpec.scala
- test/navigation/NomineesNavigatorSpec.scala
- test/pages/nominees/IsOrganisationNomineeNinoPageSpec.scala
> [MS, RS][DDCE-918] Added 'Do they have NINO' page for section 9.

- app/controllers/nominees/OrganisationAuthorisedPersonNinoController.scala
- app/navigation/NomineesNavigator.scala
- app/pages/nominees/OrganisationAuthorisedPersonNinoPage.scala
- app/views/common/NinoView.scala.html
- conf/messages.cy
- conf/messages.en
- conf/officialsAndNominees.routes
- test/controllers/nominees/OrganisationAuthorisedPersonNinoControllerSpec.scala
- test/navigation/NomineesNavigatorSpec.scala
- test/pages/nominees/OrganisationAuthorisedPersonNinoPageSpec.scala
> [RS][DDCE-920] Added organisation auth person NINO page.

- app/controllers/operationsAndFunds/WhatCountryDoesTheCharityOperateInController.scala
> DDCE-1176: changes to fix journey to 'remove' operating country

- app/controllers/nominees/NomineeDetailsSummaryController.scala
- app/models/nominees/NomineeSummary.scala
- app/navigation/NomineesNavigator.scala
- app/viewmodels/CheckYourAnswersHelper.scala
- app/viewmodels/nominees/NomineeIndividualSummaryHelper.scala
- app/viewmodels/nominees/NomineeOrganisationSummaryHelper.scala
- app/viewmodels/nominees/NomineeTypeSummaryHelper.scala
- app/viewmodels/operationsAndFunds/BankDetailsSummaryHelper.scala
- app/views/components/inputDate.scala.html
- app/views/nominees/NomineeDetailsSummaryView.scala.html
- conf/messages.cy
- conf/messages.en
- test/navigation/NomineesNavigatorSpec.scala
- test/viewModels/nominees/NomineeIndividualSummaryHelperSpec.scala
- test/viewModels/nominees/NomineeOrganisationSummaryHelperSpec.scala
- test/viewModels/nominees/NomineeTypeSummaryHelperSpec.scala
- test/viewModels/operationsAndFunds/BankDetailsSummaryHelperSpec.scala
> [RS][DDCE-921] Added nominee summaries.

- app/controllers/operationsAndFunds/OverseasOperatingLocationSummaryController.scala
- app/navigation/FundRaisingNavigator.scala
- app/viewmodels/operationsAndFunds/OperationsFundsSummaryHelper.scala
- app/viewmodels/operationsAndFunds/OverseasOperatingLocationSummaryHelper.scala
- test/navigation/FundRaisingNavigatorSpec.scala
- test/viewModels/operationsAndFunds/OverseasOperatingLocationSummaryHelperSpec.scala
> DDCE-1176: changes to fix journey to 'remove' operating country in both mode

- app/controllers/addressLookup/NomineeIndividualPreviousAddressLookupController.scala
- app/controllers/operationsAndFunds/OverseasOperatingLocationSummaryController.scala
- app/navigation/FundRaisingNavigator.scala
- app/navigation/NomineesNavigator.scala
- app/pages/addressLookup/NomineeIndividualPreviousAddressLookupPage.scala
- app/viewmodels/nominees/NomineeIndividualSummaryHelper.scala
- conf/address.routes
- conf/messages.cy
- conf/messages.en
- test/controllers/addressLookup/NomineeIndividualPreviousAddressLookupControllerSpec.scala
- test/controllers/operationsAndFunds/OverseasOperatingLocationSummaryControllerSpec.scala
- test/navigation/FundRaisingNavigatorSpec.scala
- test/navigation/NomineesNavigatorSpec.scala
- test/pages/addressLookup/NomineeIndividualPreviousAddressLookupPageSpec.scala
- test/viewModels/nominees/NomineeIndividualSummaryHelperSpec.scala
> [RS][DDCE-1189] Added previous address lookup for individual nominee.

- app/controllers/nominees/IndividualNomineePassportController.scala
- app/controllers/nominees/NomineeDetailsSummaryController.scala
- app/navigation/NomineesNavigator.scala
- app/pages/nominees/IndividualNomineesPassportPage.scala
- app/viewmodels/nominees/NomineeIndividualSummaryHelper.scala
- conf/messages.cy
- conf/messages.en
- conf/officialsAndNominees.routes
- test/controllers/nominees/IndividualNomineePassportControllerSpec.scala
- test/navigation/NomineesNavigatorSpec.scala
- test/pages/nominees/IndividualNomineePassportPageSpec.scala
- test/viewModels/nominees/NomineeIndividualSummaryHelperSpec.scala
Authorised Persons Passport details
> DDCE- 1181:Authorised Persons Passport details

- app/controllers/addressLookup/OrganisationNomineePreviousAddressLookupController.scala
- app/navigation/NomineesNavigator.scala
- app/pages/addressLookup/OrganisationNomineePreviousAddressLookupPage.scala
- conf/address.routes
- conf/messages.cy
- conf/messages.en
- test/controllers/addressLookup/OrganisationNomineePreviousAddressLookupControllerSpec.scala
- test/navigation/NomineesNavigatorSpec.scala
- test/pages/addressLookup/OrganisationNomineePreviousAddressLookupPageSpec.scala
> DDCE-1190: changes for  Organisation Previous Address Lookup

- app/controllers/nominees/NomineeDetailsSummaryController.scala
- app/controllers/nominees/OrganisationAuthorisedPersonPassportController.scala
- app/navigation/FundRaisingNavigator.scala
- app/navigation/NomineesNavigator.scala
- app/pages/nominees/OrganisationAuthorisedPersonPassportPage.scala
- app/viewmodels/nominees/NomineeOrganisationSummaryHelper.scala
- conf/messages.cy
- conf/messages.en
- conf/officialsAndNominees.routes
- test/controllers/nominees/OrganisationAuthorisedPersonPassportControllerSpec.scala
- test/navigation/NomineesNavigatorSpec.scala
- test/pages/nominees/OrganisationAuthorisedPersonPassportPageSpec.scala
- test/viewModels/nominees/NomineeOrganisationSummaryHelperSpec.scala
> [RS][DDCE-1182] Added passport page for org nominee auth person.

- app/controllers/common/AddedOfficialController.scala
- app/navigation/OtherOfficialsNavigator.scala
- app/pages/otherOfficials/IsOtherOfficialNinoPage.scala
- app/pages/otherOfficials/IsOtherOfficialsPreviousAddressPage.scala
- app/viewmodels/authorisedOfficials/AddedOfficialsSummaryHelper.scala
- app/viewmodels/otherOfficials/AddedOneOtherOfficialHelper.scala
- test/navigation/OtherOfficialsNavigatorSpec.scala
- test/viewModels/otherOfficials/AddedOneOtherOfficialHelperSpec.scala
> DDCE-1042:Check the other official’s details

- app/navigation/FundRaisingNavigator.scala
- app/pages/operationsAndFunds/FundRaisingPage.scala
- app/pages/operationsAndFunds/IsBankStatementsPage.scala
- app/pages/operationsAndFunds/OperatingLocationPage.scala
- app/viewmodels/operationsAndFunds/OperationsFundsSummaryHelper.scala
- test/navigation/FundRaisingNavigatorSpec.scala
- test/viewModels/operationsAndFunds/OperationsFundsSummaryHelperSpec.scala
> [RS][DDCE-1168] Hooked up all section 5 change links.

- app/controllers/nominees/NomineeDetailsSummaryController.scala
- app/navigation/AuthorisedOfficialsNavigator.scala
- test/controllers/nominees/NomineeDetailsSummaryControllerSpec.scala
- test/navigation/AuthorisedOfficialsNavigatorSpec.scala
- test/navigation/ExternalTestNavigationSpec.scala
> DDCE-1166: Navigation chages for Summary Page 'Change' Journeys

- app/controllers/authorisedOfficials/AuthorisedOfficialsSummaryController.scala
- app/controllers/otherOfficials/OtherOfficialsSummaryController.scala
- app/navigation/OtherOfficialsNavigator.scala
- app/viewmodels/authorisedOfficials/AddedOfficialsSummaryHelper.scala
- app/views/common/OfficialsSummaryView.scala.html
- test/navigation/OtherOfficialsNavigatorSpec.scala
##New feature
Summary Page with 3 other officials
> DDCE-1157:Summary Page with 3 other officials

- app/controllers/actions/IdentifierAction.scala
- app/navigation/NomineesNavigator.scala
- test/controllers/actions/AuthActionSpec.scala
- test/navigation/ExternalTestNavigationSpec.scala
> DDCE-1195: Skip Login in External Test Journey

- app/views/common/OfficialsSummaryView.scala.html
- app/views/components/inputRadio.scala.html
##Bug fix
Change radio button layout to match prototype
> DDCE-1184:Change radio button layout to match prototype

- app/controllers/actions/IdentifierAction.scala
- test/controllers/actions/AuthActionSpec.scala
> DDCE-1195: issue fixed for user journeys

- app/controllers/addressLookup/OrganisationNomineeAddressLookupController.scala
- app/controllers/addressLookup/OtherOfficialsPreviousAddressLookupController.scala
- app/controllers/nominees/IndividualNomineesPhoneNumberController.scala
- app/navigation/OtherOfficialsNavigator.scala
- conf/officialsAndNominees.routes
- test/navigation/ExternalTestNavigationSpec.scala
- test/navigation/OtherOfficialsNavigatorSpec.scala
> DDCE-1177: changes to update summary Page 'Change' Journeys

- app/controllers/charityInformation/CharityInformationSummaryController.scala
- app/models/UserAnswers.scala
- app/pages/operationsAndFunds/OperatingLocationPage.scala
- test/controllers/charityInformation/CharityInformationSummaryControllerSpec.scala
> [RS][DDCE-619] Section 1: tag based on actual completeness of section.

- app/views/authorisedOfficials/CharityAuthorisedOfficialsView.scala.html
- app/views/charityInformation/StartInformationView.scala.html
- app/views/nominees/CharityNomineeView.scala.html
- app/views/operationsAndFunds/StartCharitableObjectivesView.scala.html
- app/views/operationsAndFunds/StartFundraisingView.scala.html
- app/views/otherOfficials/AddSecondOtherOfficialsView.scala.html
- app/views/otherOfficials/CharityOtherOfficialsView.scala.html
- app/views/regulatorsAndDocuments/StartCharityRegulatorView.scala.html
- app/views/regulatorsAndDocuments/StartGoverningDocumentView.scala.html
- conf/messages.cy
- conf/messages.en
- test/views/authorisedOfficials/CharityAuthorisedOfficialsViewSpec.scala
- test/views/charityInformation/StartInformationViewSpec.scala
- test/views/nominees/CharityNomineeViewSpec.scala
- test/views/operationsAndFunds/StartCharitableObjectivesViewSpec.scala
- test/views/operationsAndFunds/StartFundraisingViewSpec.scala
- test/views/otherOfficials/AddSecondOtherOfficialsViewSpec.scala
- test/views/otherOfficials/CharityOtherOfficialsViewSpec.scala
- test/views/regulatorsAndDocuments/StartCharityRegulatorViewSpec.scala
- test/views/regulatorsAndDocuments/StartGoverningDocumentViewSpec.scala
##New feature
Content Updates - Amend H1s on all pages with multiple fields
> DDCE-1160:Content Updates - Amend H1s on all pages with multiple fields

- app/controllers/regulatorsAndDocuments/GoverningDocumentSummaryController.scala
- app/models/UserAnswers.scala
- app/navigation/NomineesNavigator.scala
- app/viewmodels/regulatorsAndDocuments/GoverningDocumentStatusHelper.scala
- app/views/templates/GovukLayoutWrapper.scala.html
- test/controllers/regulatorsAndDocuments/GoverningDocumentSummaryControllerSpec.scala
- test/navigation/NomineesNavigatorSpec.scala
- test/viewModels/GoverningDocumentStatusHelperSpec.scala
> DDCE-1200: changes to make Section 3 Status Tag update from Data

- app/controllers/operationsAndFunds/BankDetailsSummaryController.scala
- app/viewmodels/operationsAndFunds/BankDetailsStatusHelper.scala
- test/controllers/operationsAndFunds/BankDetailsSummaryControllerSpec.scala
- test/viewModels/operationsAndFunds/BankDetailsStatusHelperSpec.scala
Make Section 6 Status Tag update from Data
> DDCE-1203:Make Section 6 Status Tag update from Data

- app/config/FrontendAppConfig.scala
- app/controllers/charityInformation/CharityInformationSummaryController.scala
- app/controllers/operationsAndFunds/BankDetailsSummaryController.scala
- app/controllers/operationsAndFunds/OperationsFundsSummaryController.scala
- app/pages/operationsAndFunds/OperatingLocationPage.scala
- app/pages/operationsAndFunds/OverseasCountriesPage.scala
- app/pages/operationsAndFunds/WhatCountryDoesTheCharityOperateInDeletePage.scala
- app/viewmodels/operationsAndFunds/OperationsFundsStatusHelper.scala
- app/viewmodels/regulatorsAndDocuments/GoverningDocumentStatusHelper.scala
- app/views/templates/GovukLayoutWrapper.scala.html
- test/config/FrontendAppConfigSpec.scala
- test/connectors/addressLookup/AddressLookupConnectorSpec.scala
- test/controllers/operationsAndFunds/BankDetailsSummaryControllerSpec.scala
- test/pages/operationsAndFunds/OverseasCountriesPageSpec.scala
- test/viewModels/operationsAndFunds/OperationsFundsStatusHelperSpec.scala
- test/viewModels/operationsAndFunds/OperationsFundsSummaryHelperSpec.scala
- test/viewModels/regulatorsAndDocuments/GoverningDocumentStatusHelperSpec.scala
> DDCE-1202: changes for Make Section 5 Status Tag update from Data

- app/controllers/operationsAndFunds/WhatCountryDoesTheCharityOperateInController.scala
- app/navigation/FundRaisingNavigator.scala
- test/navigation/FundRaisingNavigatorSpec.scala
> DDCE-1202: fix for status and navigation of section 5

- app/controllers/authorisedOfficials/AuthorisedOfficialsSummaryController.scala
- app/controllers/charityInformation/CharityInformationSummaryController.scala
- app/controllers/operationsAndFunds/OperationsFundsSummaryController.scala
- app/viewmodels/authorisedOfficials/AuthorisedOfficialsStatusHelper.scala
- app/viewmodels/operationsAndFunds/OperationsFundsStatusHelper.scala
- test/controllers/authorisedOfficials/AuthorisedOfficialsSummaryControllerSpec.scala
- test/controllers/operationsAndFunds/OperationsFundsSummaryControllerSpec.scala
- test/navigation/FundRaisingNavigatorSpec.scala
- test/viewModels/authorisedOfficials/AddedOneAuthorisedOfficialHelperSpec.scala
- test/viewModels/authorisedOfficials/AuthorisedOfficialsStatusHelperSpec.scala
> DDCE-1210: changes for Make Section 7 Status Tag update from Data

- app/controllers/operationsAndFunds/CharityObjectivesSummaryController.scala
- app/navigation/ObjectivesNavigator.scala
- app/viewmodels/authorisedOfficials/AuthorisedOfficialsStatusHelper.scala
- app/viewmodels/operationsAndFunds/CharityObjectivesStatusHelper.scala
- app/viewmodels/regulatorsAndDocuments/RegulatorsStatusHelper.scala
- test/controllers/operationsAndFunds/CharityObjectivesSummaryControllerSpec.scala
- test/navigation/ObjectivesNavigatorSpec.scala
- test/viewModels/operationsAndFunds/CharityObjectivesStatusHelperSpec.scala
> DDCE-1201:Make Section 4 Status Tag update from Data

- app/navigation/NomineesNavigator.scala
- app/pages/nominees/IsOrganisationNomineeNinoPage.scala
- app/pages/nominees/IsOrganisationNomineePaymentsPage.scala
- app/pages/nominees/IsOrganisationNomineePreviousAddressPage.scala
- app/viewmodels/nominees/NomineeOrganisationSummaryHelper.scala
- test/navigation/NomineesNavigatorSpec.scala
- test/viewModels/nominees/NomineeOrganisationSummaryHelperSpec.scala
Nominee Organisation Summary Page 'Change' Journeys
> DDCE-1186:§9 P15 - Nominee Organisation Summary Page 'Change' Journeys

- app/repositories/AbstractRepository.scala
- app/viewmodels/authorisedOfficials/AuthorisedOfficialsStatusHelper.scala
- app/viewmodels/package.scala
- app/viewmodels/regulatorsAndDocuments/GoverningDocumentStatusHelper.scala
- project/AppDependencies.scala
> DDCE-1156: library update and refactoring

- build.sbt
- project/AppDependencies.scala
> DDCE-1156: play2-reactivemongo version updated

- app/controllers/otherOfficials/OtherOfficialsSummaryController.scala
- app/navigation/OtherOfficialsNavigator.scala
- app/viewmodels/authorisedOfficials/AuthorisedOfficialsStatusHelper.scala
- app/viewmodels/otherOfficials/OtherOfficialStatusHelper.scala
- app/viewmodels/package.scala
- test/controllers/otherOfficials/OtherOfficialsSummaryControllerSpec.scala
- test/viewModels/authorisedOfficials/AuthorisedOfficialsStatusHelperSpec.scala
- test/viewModels/otherOfficials/OtherOfficialStatusHelperSpec.scala
> [RS][DDCE-1213] Added status tag checks for section 8.

- app/forms/common/DateOfBirthFormProvider.scala
- app/forms/common/PassportFormProvider.scala
- app/forms/mappings/GenericDateFormatter.scala
- app/forms/mappings/LocalDateFormatter.scala
- app/forms/mappings/LocalDateFormatterDayMonth.scala
- app/forms/mappings/Mappings.scala
- app/forms/regulatorsAndDocuments/GoverningDocumentNameFormProvider.scala
- app/forms/regulatorsAndDocuments/SectionsChangedGoverningDocumentFormProvider.scala
- app/forms/regulatorsAndDocuments/WhenGoverningDocumentApprovedFormProvider.scala
- conf/messages.cy
- conf/messages.en
- test/forms/mappings/DateMappingsSpec.scala
- test/forms/regulatorsAndDocuments/GoverningDocumentNameFormProviderSpec.scala
- test/forms/regulatorsAndDocuments/SectionsChangedGoverningDocumentFormProviderSpec.scala
> DDCE-1243:Update data validation and error messages for section three

- app/controllers/operationsAndFunds/OverseasOperatingLocationSummaryController.scala
- app/forms/mappings/LocalDateFormatterDayMonth.scala
- app/forms/mappings/Mappings.scala
- app/forms/operationsAndFunds/AccountingPeriodEndDateFormProvider.scala
- app/forms/operationsAndFunds/OtherFundRaisingFormProvider.scala
- app/forms/operationsAndFunds/WhatCountryDoesTheCharityOperateInFormProvider.scala
- app/forms/operationsAndFunds/WhyNoBankStatementFormProvider.scala
- app/navigation/FundRaisingNavigator.scala
- conf/messages.cy
- conf/messages.en
- test/forms/mappings/ConstraintsSpec.scala
- test/forms/mappings/DateMappingsDayMonthSpec.scala
- test/forms/operationsAndFunds/OtherFundRaisingFormProviderSpec.scala
- test/forms/operationsAndFunds/WhatCountryDoesTheCharityOperateInFormProviderSpec.scala
- test/forms/operationsAndFunds/WhyNoBankStatementFormProviderSpec.scala
- test/navigation/FundRaisingNavigatorSpec.scala
> DDCE-1245: changes to Update Data Validation & Error Messages of Section 5

- conf/messages.cy
- conf/messages.en
> DDCE-1247: apostrophe fixed

- app/controllers/authorisedOfficials/AuthorisedOfficialsSummaryController.scala
- app/controllers/authorisedOfficials/RemoveAuthorisedOfficialsController.scala
- app/navigation/AuthorisedOfficialsNavigator.scala
- app/pages/authorisedOfficials/RemoveAuthorisedOfficialsPage.scala
- app/viewmodels/officials/OfficialSummaryRowHelper.scala
- conf/messages.cy
- conf/messages.en
- conf/officialsAndNominees.routes
- test/controllers/authorisedOfficials/RemoveAuthorisedOfficialsControllerSpec.scala
- test/navigation/AuthorisedOfficialsNavigatorSpec.scala
- test/pages/authorisedOfficials/AuthorisedOfficialsIdSpec.scala
- test/pages/authorisedOfficials/RemoveAuthorisedOfficialsPageSpec.scala
- test/views/common/YesNoViewSpec.scala
> DDCE-1253: chages for Are you sure you want to remove

- app/models/CommonModels.scala
- app/views/common/NameView.scala.html
- app/views/components/inputRadio.scala.html
- conf/messages.cy
- conf/messages.en
- test/models/submission/CharitySubmissionTransformerSpec.scala
- test/models/submission/CharityTransformerConstants.scala
- test/models/submission/JsonTransformerSpec.scala
- test/pages/nominees/IndividualNomineeNamePageSpec.scala
- test/pages/nominees/OrganisationAuthorisedPersonNamePageSpec.scala
##New feature 
Update 'Title' Radio Buttons on Officials and Nominee Journeys
> DDCE-1212:Update 'Title' Radio Buttons on Officials and Nominee Journeys

- app/views/regulatorsAndDocuments/IsApprovedGoverningDocumentView.scala.html
- conf/messages.cy
- conf/messages.en
- test/views/regulatorsAndDocuments/IsApprovedGoverningDocumentViewSpec.scala
> DDCE-1250:Content Update

- app/controllers/otherOfficials/RemoveOtherOfficialsController.scala
- app/navigation/OtherOfficialsNavigator.scala
- app/pages/otherOfficials/RemoveOtherOfficialsPage.scala
- app/viewmodels/officials/OfficialSummaryRowHelper.scala
- conf/messages.cy
- conf/messages.en
- conf/officialsAndNominees.routes
- test/controllers/otherOfficials/RemoveOtherOfficialsControllerSpec.scala
- test/navigation/OtherOfficialsNavigatorSpec.scala
- test/pages/otherOfficials/RemoveOtherOfficialsPageSpec.scala
> DDCE-1258: changes for section 8 Are you sure you want to remove [official's full name]?

- app/forms/mappings/Formatters.scala
- app/forms/mappings/LocalDateFormatter.scala
- app/forms/mappings/LocalDateFormatterDayMonth.scala
- app/views/common/BankAccountDetailsView.scala.html
- app/views/common/PhoneNumberView.scala.html
- app/views/components/inputText.scala.html
- app/views/nominees/OrganisationNomineeContactDetailsView.scala.html
- test/forms/behaviours/DateBehaviours.scala
- test/forms/common/DateOfBirthFormProviderSpec.scala
> [RS][DDCE-1218] Updated inputmodes for input fields.

- app/assets/stylesheets/application.scss
- app/forms/mappings/LocalDateFormatterDayMonth.scala
- app/utils/TaskListHelper.scala
- app/views/TaskList.scala.html
- conf/messages.cy
- conf/messages.en
- test/utils/TaskListHelperSpec.scala
- test/views/TaskListViewSpec.scala
> DDCE-1299: changes to implement Updated Task List Design

- app/controllers/IndexController.scala
> DDCE-1299: status complete fix to hide message at the bottom of page

- app/controllers/StartDeclarationController.scala
- app/utils/TaskListHelper.scala
- app/views/StartDeclarationView.scala.html
- conf/app.routes
- conf/messages.cy
- conf/messages.en
- it/controllers/DeclarationControllerISpec.scala
- test/controllers/StartDeclarationControllerSpec.scala
- test/utils/TaskListHelperSpec.scala
- test/views/StartDeclarationViewSpec.scala
- test/views/TaskListViewSpec.scala
##New feature
Declaration Warm-up & URL Change
> DDCE- 1271:Declaration Warm-up & URL Change

- app/controllers/actions/IdentifierAction.scala
> DDCE-1262: Remove references to company-auth-frontend on the new charities service

- app/config/FrontendAppConfig.scala
- app/controllers/actions/IdentifierAction.scala
- conf/application.conf
- test/config/FrontendAppConfigSpec.scala
> DDCE-1262: continue url key for basegateway frontend

- app/controllers/charityInformation/CharityNameController.scala
- app/controllers/operationsAndFunds/BankDetailsController.scala
- app/forms/common/BankDetailsFormProvider.scala
- app/navigation/BankDetailsNavigator.scala
- app/navigation/CharityInformationNavigator.scala
- app/views/components/inputNumber.scala.html
- app/views/components/inputText.scala.html
- app/views/operationsAndFunds/BankDetailsView.scala.html
- conf/charityInformation.routes
- conf/messages.cy
- conf/messages.en
- test/controllers/charityInformation/CharityNameControllerSpec.scala
- test/controllers/operationsAndFunds/BankDetailsControllerSpec.scala
- test/forms/common/BankDetailsFormProviderSpec.scala
- test/navigation/CharityInformationNavigatorSpec.scala
- test/views/operationsAndFunds/BankDetailsViewSpec.scala
> DDCE-1326: Implement updated design for P1 - The charity’s bank, building society or credit union details

- app/controllers/operationsAndFunds/CharityEstablishedInController.scala
- app/forms/operationsAndFunds/CharityEstablishedInFormProvider.scala
- app/models/operations/CharityEstablishedOptions.scala
- app/models/submission/CharityCommonTransformer.scala
- app/models/submission/CharityTransformer.scala
- app/navigation/FundRaisingNavigator.scala
- app/pages/operationsAndFunds/CountryEstablishedInPage.scala
- app/viewmodels/operationsAndFunds/OperationsFundsStatusHelper.scala
- app/viewmodels/operationsAndFunds/OperationsFundsSummaryHelper.scala
- app/views/operationsAndFunds/CharityEstablishedInView.scala.html
- conf/messages.cy
- conf/messages.en
- conf/operationsAndFunds.routes
- it/resources/request_with_min_data.json
- it/resources/scenario_1_request.json
- it/resources/scenario_2_request.json
- it/resources/scenario_3_request.json
- test/controllers/operationsAndFunds/WhatCountryWasTheCharityEstablishedInControllerSpec.scala
- test/forms/operationsAndFunds/WhatCountryWasTheCharityEstablisedInFormProviderSpec.scala
- test/models/operations/CharityEstablishedInSpec.scala
- test/models/submission/CharityCommonTransformerSpec.scala
- test/models/submission/CharitySubmissionTransformerSpec.scala
- test/models/submission/CharityTransformerConstants.scala
- test/navigation/FundRaisingNavigatorSpec.scala
- test/pages/operationsAndFunds/CountryEstablishedInPageSpec.scala
- test/viewModels/operationsAndFunds/OperationsFundsStatusHelperSpec.scala
- test/viewModels/operationsAndFunds/OperationsFundsSummaryHelperSpec.scala
- test/views/operationsAndFunds/WhatCountryWasCharityEstablishedInViewSpec.scala
##New feature
What country was the charity established in?
> DDCE-1335:What country was the charity established in?

- app/config/FrontendAppConfig.scala
- app/config/ModuleBindings.scala
- app/connectors/CharitiesShortLivedCache.scala
- app/models/oldCharities/OldCharities.scala
- app/service/CharitiesKeyStoreService.scala
- build.sbt
- conf/application.conf
- project/AppDependencies.scala
- test/config/FrontendAppConfigSpec.scala
- test/connectors/CharitiesConnectorSpec.scala
- test/connectors/CharitiesShortLivedCacheSpec.scala
- test/connectors/WireMockHelper.scala
- test/resources/keyStore_response_1.json
- test/service/CharitiesKeyStoreServiceSpec.scala
> DDCE-1335: Implement pulling data using CredID and decrypt or normalise it

- app/config/FrontendAppConfig.scala
- conf/application.conf
- test/config/FrontendAppConfigSpec.scala
> [RS][DDCE-1325] Changed GTM snippet & fixed content security policy.

- app/controllers/operationsAndFunds/WhatCountryDoesTheCharityOperateInController.scala
- app/views/operationsAndFunds/WhatCountryDoesTheCharityOperateInView.scala.html
- conf/messages.cy
- conf/messages.en
- test/controllers/operationsAndFunds/WhatCountryDoesTheCharityOperateInControllerSpec.scala
- test/views/operationsAndFunds/WhatCountryDoesTheCharityOperateInViewSpec.scala
> DDCE-1336: Updated Country Selection Page

- app/forms/charityInformation/CharityNameFormProvider.scala
- app/forms/common/BankDetailsFormProvider.scala
- app/forms/mappings/Mappings.scala
- app/forms/operationsAndFunds/CharitableObjectivesFormProvider.scala
- app/forms/operationsAndFunds/OtherFundRaisingFormProvider.scala
- app/forms/operationsAndFunds/PublicBenefitsFormProvider.scala
- app/forms/operationsAndFunds/WhyNoBankStatementFormProvider.scala
- app/forms/regulatorsAndDocuments/CharityOtherRegulatorDetailsFormProvider.scala
- app/forms/regulatorsAndDocuments/GoverningDocumentNameFormProvider.scala
- app/forms/regulatorsAndDocuments/ScottishRegulatorRegNumberFormProvider.scala
- app/forms/regulatorsAndDocuments/SectionsChangedGoverningDocumentFormProvider.scala
- app/forms/regulatorsAndDocuments/WhyNotRegisteredWithCharityFormProvider.scala
- app/views/operationsAndFunds/PublicBenefitsView.scala.html
- conf/messages.cy
- conf/messages.en
- test/forms/charityInformation/CharityNameFormProviderSpec.scala
- test/forms/common/BankDetailsFormProviderSpec.scala
- test/forms/operationsAndFunds/CharitableObjectivesFormProviderSpec.scala
- test/forms/operationsAndFunds/OtherFundRaisingFormProviderSpec.scala
- test/forms/operationsAndFunds/PublicBenefitsFormProviderSpec.scala
- test/forms/operationsAndFunds/WhyNoBankStatementFormProviderSpec.scala
- test/forms/regulatorsAndDocuments/CharityOtherRegulatorDetailsFormProviderSpec.scala
- test/forms/regulatorsAndDocuments/GoverningDocumentNameFormProviderSpec.scala
- test/forms/regulatorsAndDocuments/SectionsChangedGoverningDocumentFormProviderSpec.scala
- test/forms/regulatorsAndDocuments/WhyNotRegisteredWithCharityFormProviderSpec.scala
##New feature 
Correct Data Validations & Error Messages
> DDCE-1345:Correct Data Validations & Error Messages

- app/config/FrontendAppConfig.scala
- app/repositories/AbstractRepository.scala
- app/repositories/SessionRepository.scala
- app/repositories/UserAnswerRepository.scala
- conf/application.conf
- project/AppDependencies.scala
- test/config/FrontendAppConfigSpec.scala
- test/repositories/MongoUnitSpec.scala
- test/repositories/UserAnswerRepositorySpec.scala
> [RS][DDCE-1352] Added ability to encrypt user data in database.

- app/controllers/IndexController.scala
- app/models/oldCharities/OldCharities.scala
- app/models/oldCharities/UserAnswerTransformer.scala
- app/models/oldCharities/package.scala
- app/models/submission/CharityCommonTransformer.scala
- app/service/CharitiesKeyStoreService.scala
- app/viewmodels/charityInformation/CharityInformationStatusHelper.scala
- app/viewmodels/operationsAndFunds/OverseasOperatingLocationSummaryHelper.scala
- test/controllers/IndexControllerSpec.scala
- test/models/oldCharities/UserAnswerTransformerSpec.scala
- test/service/CharitiesKeyStoreServiceSpec.scala
- test/viewModels/charityInformation/CharityInformationStatusHelperSpec.scala
> DDCE-1305: Implement transformations for first 8 sections

- app/controllers/IndexController.scala
- app/models/oldCharities/UserAnswerTransformer.scala
- app/service/CharitiesKeyStoreService.scala
- test/controllers/IndexControllerSpec.scala
- test/service/CharitiesKeyStoreServiceSpec.scala
> DDCE-1307: Implement deletion of old data in existing service after transfer to new service

- conf/messages.cy
- conf/messages.en
> DDCE-1343: Updated Message File

- app/views/common/CurrencyView.scala.html
- app/views/common/DateOfBirthView.scala.html
- app/views/common/PassportView.scala.html
- app/views/components/inputDate.scala.html
- app/views/operationsAndFunds/AccountingPeriodEndDateView.scala.html
- app/views/regulatorsAndDocuments/WhenGoverningDocumentApprovedView.scala.html
##New feature
Correct Error Message Red Bar Length
> DDCE-1339:Correct Error Message Red Bar Length

- app/views/components/autocompleteCountryList.scala.html
> DDCE-1339New:Correct Error Message Red Bar Length

- app/controllers/DeclarationController.scala
- app/models/oldCharities/OldCharities.scala
- app/service/CharitiesKeyStoreService.scala
- app/transformers/UserAnswerTransformer.scala
- app/transformers/package.scala
- app/transformers/submission/CharityCommonTransformer.scala
- app/transformers/submission/CharityPartnerTransformer.scala
- app/transformers/submission/CharitySubmissionTransformer.scala
- app/transformers/submission/CharityTransformer.scala
- app/transformers/submission/JsonTransformer.scala
- test/controllers/DeclarationControllerSpec.scala
- test/transformers/UserAnswerTransformerSpec.scala
- test/transformers/submission/CharityCommonTransformerSpec.scala
- test/transformers/submission/CharityPartnerTransformerSpec.scala
- test/transformers/submission/CharitySubmissionTransformerSpec.scala
- test/transformers/submission/CharityTransformerConstants.scala
- test/transformers/submission/CharityTransformerSpec.scala
- test/transformers/submission/JsonTransformerSpec.scala
> new package added for all the json transformers

- app/config/FrontendAppConfig.scala
- app/connectors/CharitiesShortLivedCache.scala
- app/views/TaskList.scala.html
- conf/application.conf
- test/config/FrontendAppConfigSpec.scala
- test/connectors/CharitiesShortLivedCacheSpec.scala
> DDCE-1361: Change pulling data to pull from Save4Later rather than Keystore

- app/controllers/IndexController.scala
- app/models/oldCharities/OldCharities.scala
- app/models/transformers/TransformerKeeper.scala
- app/service/CharitiesKeyStoreService.scala
- app/transformers/UserAnswerTransformer.scala
- app/transformers/package.scala
- app/views/RegistrationSentView.scala.html
- conf/app.routes
- test/controllers/IndexControllerSpec.scala
- test/service/CharitiesKeyStoreServiceSpec.scala
- test/transformers/UserAnswerTransformerSpec.scala
- test/views/RegistrationSentViewSpec.scala
> [RS][DDCE-1332] Hooking up authorised official pulling from old service.

- app/views/components/inputRadio.scala.html
- app/views/nominees/ChooseNomineeView.scala.html
##Bug fix 
Error Message Not Redirecting
> DDCE-1367:Error Message Not Redirecting

- app/models/oldCharities/OldCharities.scala
- app/service/CharitiesKeyStoreService.scala
- app/transformers/UserAnswerTransformer.scala
- app/transformers/package.scala
- app/viewmodels/otherOfficials/OtherOfficialStatusHelper.scala
- test/service/CharitiesKeyStoreServiceSpec.scala
- test/transformers/CharitiesJsObjectSpec.scala
- test/transformers/UserAnswerTransformerSpec.scala
- test/viewModels/authorisedOfficials/AuthorisedOfficialsStatusHelperSpec.scala
- test/viewModels/otherOfficials/OtherOfficialStatusHelperSpec.scala
> [RS][DDCE-1333] Hooking up other official pulling from old service.

- app/models/oldCharities/OldCharities.scala
- app/service/CharitiesKeyStoreService.scala
- app/transformers/UserAnswerTransformer.scala
- app/viewmodels/nominees/NomineeStatusHelper.scala
- test/service/CharitiesKeyStoreServiceSpec.scala
- test/transformers/UserAnswerTransformerSpec.scala
- test/utils/TestData.scala
- test/viewModels/nominees/NomineeStatusHelperSpec.scala
> DDCE-1334: Implement transformations for nominees sections

- app/controllers/RegistrationSentController.scala
- app/models/oldCharities/OldCharities.scala
- app/pages/ApplicationSubmissionDatePage.scala
- app/service/CharitiesKeyStoreService.scala
- app/service/CharitiesRegistrationService.scala
- app/transformers/UserAnswerTransformer.scala
- test/controllers/RegistrationSentControllerSpec.scala
- test/pages/ApplicationSubmissionDatePageSpec.scala
- test/service/CharitiesKeyStoreServiceSpec.scala
- test/transformers/UserAnswerTransformerSpec.scala
- test/utils/TestData.scala
> DDCE-1375: Store Application Submission Date and Reference Number

- app/audit/AuditService.scala
- app/controllers/IndexController.scala
- app/navigation/RegulatorsAndDocumentsNavigator.scala
- app/service/CharitiesKeyStoreService.scala
- app/service/CharitiesRegistrationService.scala
- app/transformers/UserAnswerTransformer.scala
- test/navigation/RegulatorsAndDocumentsNavigatorSpec.scala
- test/service/CharitiesKeyStoreServiceSpec.scala
- test/transformers/UserAnswerTransformerSpec.scala
- test/transformers/submission/CharityPartnerTransformerSpec.scala
- test/utils/TestData.scala
> DDCE-1376: Update the Navigations for Section 2 for switched-over users

- app/controllers/ApplicationBeingProcessedController.scala
- app/controllers/IndexController.scala
- app/controllers/RegistrationSentController.scala
- app/controllers/actions/DataRequiredAction.scala
- app/controllers/actions/RegistrationDataRequiredAction.scala
- app/models/OldServiceSubmission.scala
- app/models/oldCharities/OldCharities.scala
- app/pages/OldServiceSubmissionPage.scala
- app/repositories/AbstractRepository.scala
- app/service/CharitiesKeyStoreService.scala
- app/transformers/UserAnswerTransformer.scala
- app/utils/ImplicitDateFormatter.scala
- app/views/ApplicationBeingProcessedView.scala.html
- app/views/RegistrationSentView.scala.html
- conf/app.routes
- conf/messages.cy
- conf/messages.en
- test/controllers/ApplicationBeingProcessedControllerSpec.scala
- test/controllers/EmailOrPostControllerSpec.scala
- test/controllers/IndexControllerSpec.scala
- test/controllers/RegistrationSentControllerSpec.scala
- test/controllers/charityInformation/CharityNameControllerSpec.scala
- test/pages/OldServiceSubmissionPageSpec.scala
- test/service/CharitiesKeyStoreServiceSpec.scala
- test/transformers/UserAnswerTransformerSpec.scala
- test/utils/TestData.scala
- test/views/ApplicationBeingProcessedViewSpec.scala
> [RS][DDCE-1379] Registration sent page if completed  in old service.

- app/controllers/operationsAndFunds/IsRemoveOperatingCountryController.scala
- app/controllers/operationsAndFunds/WhatCountryDoesTheCharityOperateInController.scala
- app/pages/operationsAndFunds/IsRemoveOperatingCountryPage.scala
- app/viewmodels/operationsAndFunds/OverseasOperatingLocationSummaryHelper.scala
- app/views/common/YesNoView.scala.html
- conf/messages.cy
- conf/messages.en
- conf/operationsAndFunds.routes
- test/controllers/operationsAndFunds/IsRemoveOperatingCountryControllerSpec.scala
- test/pages/operationsAndFunds/IsRemoveOperatingCountryPageSpec.scala
- test/viewModels/operationsAndFunds/OverseasOperatingLocationSummaryHelperSpec.scala
> [JR,AA,RS][DDCE-1349] Are you sure you want to remove [country]? Page

- app/controllers/LocalBaseController.scala
- app/controllers/charityInformation/ConfirmCharityOfficialAddressController.scala
- app/controllers/charityInformation/ConfirmCharityPostalAddressController.scala
- app/controllers/common/ConfirmAddressController.scala
- app/navigation/CharityInformationNavigator.scala
- app/views/charityInformation/CanWeSendToThisAddressView.scala.html
- app/views/common/ConfirmAddressView.scala.html
- conf/charityInformation.routes
- test/controllers/charityInformation/ConfirmCharityOfficialAddressControllerSpec.scala
- test/controllers/charityInformation/ConfirmCharityPostalAddressControllerSpec.scala
- test/navigation/CharityInformationNavigatorSpec.scala
- test/views/common/ConfirmAddressViewSpec.scala
> DDCE-1359: Implement Address Playback Pages for Section 1 and make component reusable

- app/assets/stylesheets/application.scss
- app/viewmodels/OfficialSummaryListRow.scala
- app/viewmodels/authorisedOfficials/AuthorisedOfficialsStatusHelper.scala
- app/viewmodels/officials/OfficialSummaryRowHelper.scala
- app/viewmodels/otherOfficials/OtherOfficialStatusHelper.scala
- app/views/common/OfficialsSummaryView.scala.html
- test/viewModels/authorisedOfficials/AuthorisedOfficialsStatusHelperSpec.scala
- test/viewModels/otherOfficials/OtherOfficialStatusHelperSpec.scala
> DDCE-1337: §7 & §8 Implement Status Tags in Summary Page

- app/controllers/DeclarationController.scala
- app/controllers/IndexController.scala
- app/controllers/RegistrationSentController.scala
- app/controllers/authorisedOfficials/AuthorisedOfficialsSummaryController.scala
- app/controllers/charityInformation/CharityInformationSummaryController.scala
- app/controllers/nominees/NomineeDetailsSummaryController.scala
- app/controllers/otherOfficials/OtherOfficialsSummaryController.scala
- project/AppDependencies.scala
- test/controllers/IndexControllerSpec.scala
- test/controllers/LocalBaseControllerSpec.scala
- test/controllers/RegistrationSentControllerSpec.scala
- test/controllers/authorisedOfficials/AuthorisedOfficialsSummaryControllerSpec.scala
- test/controllers/charityInformation/CharityInformationSummaryControllerSpec.scala
- test/controllers/nominees/NomineeDetailsSummaryControllerSpec.scala
- test/controllers/operationsAndFunds/WhatCountryDoesTheCharityOperateInControllerSpec.scala
- test/controllers/otherOfficials/OtherOfficialsSummaryControllerSpec.scala
> DDCE-1383: Ensure updated charities rewrite is on the external test environment

- app/utils/ImplicitDateFormatter.scala
- conf/prod.routes
- project/AppDependencies.scala
- test/utils/ImplicitDateFormatterSpec.scala
> DDCE-1388: Remove ordinal suffixes from Welsh translated dates

- app/navigation/AuthorisedOfficialsNavigator.scala
- app/viewmodels/CheckYourAnswersHelper.scala
- app/viewmodels/OfficialSummaryListRow.scala
- app/viewmodels/authorisedOfficials/AuthorisedOfficialsStatusHelper.scala
- app/viewmodels/otherOfficials/OtherOfficialStatusHelper.scala
- test/utils/ImplicitDateFormatterSpec.scala
- test/viewModels/authorisedOfficials/AddedAuthorisedOfficialHelperSpec.scala
Reverts hmrc/charities-registration-frontend#357
> Revert "[RS][DDCE-1357] Fixed display of unauthorised titles for switchover u…"

- app/navigation/AuthorisedOfficialsNavigator.scala
- app/viewmodels/CheckYourAnswersHelper.scala
- app/viewmodels/OfficialSummaryListRow.scala
- app/viewmodels/authorisedOfficials/AuthorisedOfficialsStatusHelper.scala
- app/viewmodels/otherOfficials/OtherOfficialStatusHelper.scala
- test/utils/ImplicitDateFormatterSpec.scala
- test/viewModels/authorisedOfficials/AddedAuthorisedOfficialHelperSpec.scala
Previous PR was accidentally merged in. This is the same PR, reopened.
> [RS][DDCE-1357] Fixed display of unauthorised titles for switchover.

- app/viewmodels/RequiredDocumentsHelper.scala
- conf/messages.cy
- test/viewModels/RequiredDocumentsHelperSpec.scala
> DDCE-1347: Updated Welsh method for listing names for identity details

- app/utils/ImplicitDateFormatter.scala
- test/utils/ImplicitDateFormatterSpec.scala
> DDCE-1407: Remove ordinal suffixes from dates throughout the rewrite

- conf/messages.cy
- conf/messages.en
> DDCE-1406: Update 'bank welcome letter' content to '1 month's statement'

- app/controllers/SwitchOverErrorController.scala
- app/service/CharitiesSave4LaterService.scala
- app/transformers/package.scala
- app/views/SwitchOverErrorView.scala.html
- conf/app.routes
- conf/messages.cy
- conf/messages.en
- test/controllers/SwitchOverErrorControllerSpec.scala
- test/service/CharitiesSave4LaterServiceSpec.scala
- test/views/SwitchOverErrorViewSpec.scala
> DDCE-1386: Implement new error page for switched-over users

- app/navigation/AuthorisedOfficialsNavigator.scala
- app/navigation/OtherOfficialsNavigator.scala
- app/utils/TaskListHelper.scala
> DDCE-1395: Change navigation from the Section 7 & 8 summaries

- app/views/RegistrationSentView.scala.html
- app/views/checkEligibility/IsEligibleLocationOtherView.scala.html
- conf/messages.cy
- conf/messages.en
> [RS][DDCE-1426] Added Welsh translations.

- app/views/templates/GovukLayoutWrapper.scala.html
> [RS][DDCE-1426] Fixed the technical issue link language.

- app/models/regulators/SelectGoverningDocument.scala
- app/transformers/UserAnswerTransformer.scala
- app/views/templates/GovukLayoutWrapper.scala.html
- conf/messages.cy
- conf/messages.en
- test/controllers/regulatorsAndDocuments/WhenGoverningDocumentApprovedControllerSpec.scala
- test/service/CharitiesSave4LaterServiceSpec.scala
- test/transformers/UserAnswerTransformerSpec.scala
- test/transformers/submission/CharityTransformerConstants.scala
- test/transformers/submission/CharityTransformerSpec.scala
- test/views/regulatorsAndDocuments/WhenGoverningDocumentApprovedViewSpec.scala
> [RS][DDCE-1437] Fixed the documentEnclosed to match schema.

- conf/messages.cy
- conf/messages.en
> [RS][DDCE-1464] Amended Welsh messages.

- README.md
> DDCE-1411: updated readme for service

- app/assets/stylesheets/application.scss
- app/views/common/OfficialsSummaryView.scala.html
> DDCE-1408: Fix alignment of status tags on officials summary pages

- conf/messages.cy
This is awaiting final WLU confirmation! Will open the PR once we get the go-ahead.
> [RS][DDCE-1429] Updated Welsh messages based on WLU advice.

- .gitignore
- app/views/RegistrationSentView.scala.html
- conf/messages.cy
- conf/messages.en
- test/views/RegistrationSentViewSpec.scala
- test/views/behaviours/ViewBehaviours.scala
> DDCE-1409 Add new link to print or download the registration sent page.

- app/service/CharitiesSave4LaterService.scala
- test/service/CharitiesSave4LaterServiceSpec.scala
> DDCE-1398: Remove deletion of old data in existing service after transfer to new service

- app/controllers/LocalBaseController.scala
- app/controllers/checkEligibility/CheckIfCanRegisterController.scala
- app/controllers/regulatorsAndDocuments/HasCharityChangedPartsOfGoverningDocumentController.scala
- app/controllers/regulatorsAndDocuments/IsApprovedGoverningDocumentController.scala
- app/controllers/regulatorsAndDocuments/SectionsChangedGoverningDocumentController.scala
- app/controllers/regulatorsAndDocuments/WhenGoverningDocumentApprovedController.scala
- app/viewmodels/ErrorHandler.scala
- app/views/regulatorsAndDocuments/HasCharityChangedPartsOfGoverningDocumentView.scala.html
- app/views/regulatorsAndDocuments/IsApprovedGoverningDocumentView.scala.html
- app/views/regulatorsAndDocuments/SectionsChangedGoverningDocumentView.scala.html
- app/views/regulatorsAndDocuments/WhenGoverningDocumentApprovedView.scala.html
- conf/messages.cy
- conf/messages.en
- test/controllers/LocalBaseControllerSpec.scala
- test/controllers/regulatorsAndDocuments/HasCharityChangedPartsOfGoverningDocumentControllerSpec.scala
- test/controllers/regulatorsAndDocuments/IsApprovedGoverningDocumentControllerSpec.scala
- test/controllers/regulatorsAndDocuments/SectionsChangedGoverningDocumentControllerSpec.scala
- test/controllers/regulatorsAndDocuments/WhenGoverningDocumentApprovedControllerSpec.scala
- test/views/regulatorsAndDocuments/HasCharityChangedPartsOfGoverningDocumentViewSpec.scala
- test/views/regulatorsAndDocuments/IsApprovedGoverningDocumentViewSpec.scala
- test/views/regulatorsAndDocuments/SectionsChangedGoverningDocumentViewSpec.scala
- test/views/regulatorsAndDocuments/WhenGoverningDocumentApprovedViewSpec.scala
> DDCE-1431:Implement dynamic h1 and page titles

- app/config/FrontendAppConfig.scala
- app/viewmodels/ErrorHandler.scala
- app/views/components/FooterLinks.scala
- conf/application.conf
- conf/messages.cy
- conf/messages.en
- test/assets/messages/FooterLinksMessages.scala
- test/config/FrontendAppConfigSpec.scala
- test/controllers/checkEligibility/EligibleCharityControllerSpec.scala
- test/views/components/FooterLinksSpec.scala
> DDCE-1438: Implement non-compliant accessibility statement for the Charities Rewrite

- app/viewmodels/ErrorHandler.scala
- app/views/errors/TechnicalDifficultiesErrorView.scala.html
- conf/messages.cy
- conf/messages.en
- test/views/errors/TechnicalDifficultiesErrorViewSpec.scala
> DDCE-1387: Implement new Technical Difficulties Error Page

- app/controllers/RegistrationSentController.scala
> DDCE-1535: Correct 'send by' date to be 28 days after date of submission

- conf/messages.cy
- conf/messages.en
> [DDCE-1560]:Correct content for session expiry modal

- conf/messages.cy
- conf/messages.en
> DDCE-1539:Content updates: Charity Regulators and Financial Accounts

- app/views/RegistrationSentView.scala.html
- conf/messages.cy
- conf/messages.en
> DDCE-1528: Content update to 'next steps' by email and by post pages

- app/controllers/SwitchOverAnswersLostErrorController.scala
- app/service/CharitiesSave4LaterService.scala
- app/transformers/package.scala
- app/viewmodels/authorisedOfficials/AuthorisedOfficialsStatusHelper.scala
- app/viewmodels/otherOfficials/OtherOfficialStatusHelper.scala
- app/views/SwitchOverAnswersLostErrorView.scala.html
- conf/app.routes
- conf/messages.cy
- conf/messages.en
- test/controllers/SwitchOverAnswersLostErrorControllerSpec.scala
- test/service/CharitiesSave4LaterServiceSpec.scala
- test/transformers/CharitiesJsObjectSpec.scala
- test/views/SwitchOverAnswersLostErrorViewSpec.scala
> [DDCE-1573]:Implement new 'your answers have been lost' error page for switched-over users

- conf/messages.cy
- conf/messages.en
Charities Remove reference to email
> DDCE-1826:Charities Remove reference to email

- app/config/FrontendAppConfig.scala
- app/controllers/IndexController.scala
- conf/application.conf
- test/controllers/IndexControllerSpec.scala
> DDCE-1903: updated config to correct login continue redirect

- README.md
- app/transformers/submission/CharityTransformer.scala
- test/transformers/submission/CharityTransformerSpec.scala
> DDCE-2532:Fix issue with charities text fields data mapping

- app/views/common/CurrencyView.scala.html
- app/views/components/pAsHint.scala.html
> DDCE-2942 - Fix style for hint view

- project/AppDependencies.scala
- project/plugins.sbt
- test/base/SpecBase.scala
- test/base/data/constants/AddressModelConstants.scala
> DDCE-3663 Upgrade charities-registration-frontend to use jdk 11

- project/AppDependencies.scala
> DDCE-4382 Upgrade mongo version to 1.3

- README.md
- project/AppDependencies.scala
- project/plugins.sbt
> DDCE-4516 Update charities to use sm2

- app/controllers/checkEligibility/InEligibleLocationOtherController.scala
- conf/messages.cy
- conf/messages.en
- project/AppDependencies.scala
- Updated message at `/register-charity-hmrc/check-eligibility/not-eligible-location` when a charity is not governed by UK law
> DDCE-4509: Amend kickout for ineligible locations

- app/views/components/linkAsButton.scala.html
- project/AppDependencies.scala
> DDCE-4283 Add data module to continue button

- app/transformers/submission/CharityPartnerTransformer.scala
DDCE-7261 - Search nominee organisation with more specific way to prevent confusion between organisation name inside any of the address sections.
> DDCE-7261 - Search nominee organisation with more specific way

- conf/application.conf
- project/AppDependencies.scala
**PS:** Address lookup frontend doesn't have new branding.
> DDCE-6864 -  Implement GOV.UK Rebrand
